import type { ExamQuestion } from "@/lib/types";

export const examQuestions: ExamQuestion[] = [
  {
    id: "exam-q-01", domainId: "bp-domain-1", domainTitle: "Manage a security operations environment",
    prompt: "A Sentinel incident must be assigned to the Tier 2 queue whenever its severity becomes High. No external system needs to be called. What should you configure first?",
    options: [
      { id: "a", text: "A scheduled analytics rule" },
      { id: "b", text: "An automation rule that changes the owner" },
      { id: "c", text: "A playbook triggered manually" },
      { id: "d", text: "A Microsoft Defender XDR custom detection" },
    ],
    correctOptionId: "b",
    explanation: "Automation rules can react to incident creation or updates and change incident properties such as owner, status, severity, or tags without invoking a playbook. A playbook is appropriate when a Logic Apps workflow or external action is required.",
    references: [{ pathId: "path-7", moduleId: "p7-module-2", reason: "Review automation-rule triggers, conditions, ordering, and incident actions." }],
  },
  {
    id: "exam-q-02", domainId: "bp-domain-1", domainTitle: "Manage a security operations environment",
    prompt: "You need to collect only Windows Security events 4624 and 4625 from a defined group of servers through Azure Monitor Agent. Which configuration provides the required filtering and scope?",
    options: [
      { id: "a", text: "A data collection rule associated with the target machines" },
      { id: "b", text: "A Sentinel watchlist containing both event IDs" },
      { id: "c", text: "A workbook filtered by EventID" },
      { id: "d", text: "An incident automation rule" },
    ],
    correctOptionId: "a",
    explanation: "The Windows Security Events via AMA connector uses data collection rules to define event filtering and machine associations. Watchlists and workbooks do not control ingestion.",
    references: [{ pathId: "path-6", moduleId: "p6-module-4", reason: "Review Windows Security Events via AMA and data collection rules." }],
  },
  {
    id: "exam-q-03", domainId: "bp-domain-1", domainTitle: "Manage a security operations environment",
    prompt: "A detection must evaluate events almost immediately and the required KQL can run within the limitations of near-real-time rules. Which Sentinel analytics rule type is the best fit?",
    options: [
      { id: "a", text: "Scheduled" },
      { id: "b", text: "NRT" },
      { id: "c", text: "Fusion" },
      { id: "d", text: "Microsoft security" },
    ],
    correctOptionId: "b",
    explanation: "NRT rules run once per minute and are intended for low-latency detections. Scheduled rules offer more scheduling flexibility but introduce a larger evaluation interval.",
    references: [{ pathId: "path-7", moduleId: "p7-module-1", reason: "Compare scheduled, NRT, and other Sentinel analytics-rule types." }],
  },
  {
    id: "exam-q-04", domainId: "bp-domain-1", domainTitle: "Manage a security operations environment",
    prompt: "A high-volume table is needed for historical investigations but no real-time analytics rule or interactive hunting query depends on it. Which change most directly reduces cost while preserving long-term access?",
    options: [
      { id: "a", text: "Keep the table in Analytics and create a workbook" },
      { id: "b", text: "Move eligible data to the Data Lake tier and use asynchronous analysis" },
      { id: "c", text: "Export every incident to a watchlist" },
      { id: "d", text: "Disable total retention" },
    ],
    correctOptionId: "b",
    explanation: "Data Lake storage is designed for lower-cost historical retention and asynchronous analysis. Before moving a table, verify that no real-time detection, workbook, custom detection, or interactive investigation depends on Analytics-tier access.",
    references: [{ pathId: "path-5", moduleId: "p5-module-2", reason: "Review workspace architecture and data-retention considerations." }],
  },
  {
    id: "exam-q-05", domainId: "bp-domain-2", domainTitle: "Respond to security incidents",
    prompt: "A device is actively communicating with a confirmed command-and-control host. You must stop most network communication while retaining Defender service connectivity for continued investigation. What should you do?",
    options: [
      { id: "a", text: "Isolate the device in Microsoft Defender for Endpoint" },
      { id: "b", text: "Delete the device from inventory" },
      { id: "c", text: "Suppress the incident" },
      { id: "d", text: "Create a threat indicator without an action" },
    ],
    correctOptionId: "a",
    explanation: "Device isolation restricts network communication while maintaining the channels required for Defender for Endpoint monitoring and response. Evidence collection and other response actions can then continue in a controlled sequence.",
    references: [{ pathId: "path-2", moduleId: "p2-module-5", reason: "Review device isolation, live response, and investigation-package collection." }],
  },
  {
    id: "exam-q-06", domainId: "bp-domain-2", domainTitle: "Respond to security incidents",
    prompt: "An identity has a confirmed leaked credential and an active suspicious session. Which response sequence best addresses both immediate access and the credential risk?",
    options: [
      { id: "a", text: "Dismiss the risk and wait for the next sign-in" },
      { id: "b", text: "Revoke sessions, reset the credential, and investigate related activity" },
      { id: "c", text: "Add the user to a Sentinel watchlist only" },
      { id: "d", text: "Close the incident as informational" },
    ],
    correctOptionId: "b",
    explanation: "Revoking sessions interrupts current access, while a secure credential reset addresses the compromised secret. Related sign-ins, devices, applications, and alerts must still be investigated to establish scope and persistence.",
    references: [{ pathId: "path-1", moduleId: "module-4", reason: "Review investigation and remediation of risky users and sign-ins." }],
  },
  {
    id: "exam-q-07", domainId: "bp-domain-2", domainTitle: "Respond to security incidents",
    prompt: "An investigator needs to determine who changed a retention policy and when the change occurred. Which Microsoft Purview capability should be queried first?",
    options: [
      { id: "a", text: "Audit" },
      { id: "b", text: "Content Search" },
      { id: "c", text: "Data Loss Prevention simulation mode" },
      { id: "d", text: "Communication Compliance" },
    ],
    correctOptionId: "a",
    explanation: "Microsoft Purview Audit records user and administrator activities and is the appropriate starting point for establishing who performed a configuration change and when. Content Search focuses on locating content rather than administrative activity.",
    references: [{ pathId: "path-9", moduleId: "p9-module-3", reason: "Review Audit search, activity records, scoping, and investigation workflows." }],
  },
  {
    id: "exam-q-08", domainId: "bp-domain-2", domainTitle: "Respond to security incidents",
    prompt: "Several Defender XDR incidents appear to be part of the same campaign and require work across two teams for a week. What should coordinate the broader workflow while preserving each incident record?",
    options: [
      { id: "a", text: "A security operations case" },
      { id: "b", text: "A single merged alert" },
      { id: "c", text: "A data collection rule" },
      { id: "d", text: "An archived workbook" },
    ],
    correctOptionId: "a",
    explanation: "A security operations case coordinates work across incidents, findings, indicators, tasks, owners, and teams while each linked incident retains its own evidence, classification, and lifecycle.",
    references: [{ pathId: "path-1", moduleId: "module-2", reason: "Review coordinated incident investigation and response in Microsoft Defender XDR." }],
  },
  {
    id: "exam-q-09", domainId: "bp-domain-3", domainTitle: "Perform threat hunting",
    prompt: "You need an hourly count of failed sign-ins per user from SigninLogs. Which KQL pattern produces the required aggregation?",
    options: [
      { id: "a", text: "project UserPrincipalName, ResultType" },
      { id: "b", text: "summarize Failures=count() by UserPrincipalName, bin(TimeGenerated, 1h)" },
      { id: "c", text: "distinct TimeGenerated" },
      { id: "d", text: "sort by UserPrincipalName asc" },
    ],
    correctOptionId: "b",
    explanation: "summarize performs the aggregation, count() calculates events, and bin(TimeGenerated, 1h) groups them into hourly windows for each user.",
    references: [{ pathId: "path-4", moduleId: "p4-module-2", reason: "Review summarize, aggregation functions, and time binning in KQL." }],
  },
  {
    id: "exam-q-10", domainId: "bp-domain-3", domainTitle: "Perform threat hunting",
    prompt: "A hunt must return devices that contacted a suspicious IP but have no matching alert in the selected time window. Which join flavor is most useful for excluding devices with a match in the alert dataset?",
    options: [
      { id: "a", text: "inner" },
      { id: "b", text: "leftanti" },
      { id: "c", text: "fullouter" },
      { id: "d", text: "rightsemi" },
    ],
    correctOptionId: "b",
    explanation: "A leftanti join returns rows from the left side that have no match on the right. Place the network evidence on the left and the matching alert entities on the right.",
    references: [{ pathId: "path-4", moduleId: "p4-module-3", reason: "Review multi-table KQL and join flavors." }],
  },
  {
    id: "exam-q-11", domainId: "bp-domain-3", domainTitle: "Perform threat hunting",
    prompt: "A hunting query has repeatedly identified confirmed malicious behavior and must now generate incidents automatically. What is the most appropriate next step?",
    options: [
      { id: "a", text: "Convert the validated logic into an analytics or custom detection rule" },
      { id: "b", text: "Keep running the query manually forever" },
      { id: "c", text: "Move the results into a static watchlist and disable collection" },
      { id: "d", text: "Export the query to a workbook without a detection" },
    ],
    correctOptionId: "a",
    explanation: "Hunting is hypothesis-driven and does not inherently create alerts. Once logic is sufficiently validated and tuned, operationalize it as an appropriate detection rule with scheduling, entity mapping, severity, and incident behavior.",
    references: [{ pathId: "path-8", moduleId: "p8-module-2", reason: "Review the threat-hunting lifecycle and operationalizing validated findings." }],
  },
  {
    id: "exam-q-12", domainId: "bp-domain-3", domainTitle: "Perform threat hunting",
    prompt: "A hunt requires repeatable Python transformations, external enrichment, a process-tree visualization, and a durable record combining code and analyst reasoning. Which tool is the best fit?",
    options: [
      { id: "a", text: "A Jupyter notebook with MSTICPy" },
      { id: "b", text: "An incident title template" },
      { id: "c", text: "A data connector health alert" },
      { id: "d", text: "A static analytics-rule description" },
    ],
    correctOptionId: "a",
    explanation: "Jupyter notebooks provide a reproducible environment for multi-step acquisition, transformation, enrichment, visualization, statistics, and narrative. MSTICPy adds security-focused providers and investigation tooling.",
    references: [{ pathId: "path-8", moduleId: "p8-module-4", reason: "Review notebook-based hunting and MSTICPy capabilities." }],
  },
  {
    id: "exam-q-13", domainId: "bp-domain-1", domainTitle: "Manage a security operations environment",
    prompt: "An MDE device group must receive a different automation level and be visible only to a regional analyst team. What should define membership and access?",
    options: [{ id: "a", text: "Device-group rules and RBAC assignments" }, { id: "b", text: "A Sentinel workbook" }, { id: "c", text: "An email notification rule" }, { id: "d", text: "A threat indicator" }],
    correctOptionId: "a", explanation: "Device groups use membership rules and ranked precedence, while RBAC assignments scope analyst access. The group can then receive its own automation level.",
    references: [{ pathId: "path-2", moduleId: "p2-module-7", reason: "Review device groups, RBAC, precedence, and automation levels." }],
  },
  {
    id: "exam-q-14", domainId: "bp-domain-1", domainTitle: "Manage a security operations environment",
    prompt: "An analyst must investigate and update Sentinel incidents but must not change workspace configuration. Which built-in role is the best starting point?",
    options: [{ id: "a", text: "Microsoft Sentinel Reader" }, { id: "b", text: "Microsoft Sentinel Responder" }, { id: "c", text: "Microsoft Sentinel Contributor" }, { id: "d", text: "Owner" }],
    correctOptionId: "b", explanation: "Sentinel Responder includes incident-management capabilities beyond Reader without granting the broader configuration permissions of Contributor or Owner.",
    references: [{ pathId: "path-5", moduleId: "p5-module-2", reason: "Review Sentinel roles and least-privilege workspace access." }],
  },
  {
    id: "exam-q-15", domainId: "bp-domain-1", domainTitle: "Manage a security operations environment",
    prompt: "A SOC manager wants an interactive dashboard that combines KQL visualizations, parameters, and links to investigation resources. What should you create?",
    options: [{ id: "a", text: "A workbook" }, { id: "b", text: "A data connector" }, { id: "c", text: "A device group" }, { id: "d", text: "An automation rule" }],
    correctOptionId: "a", explanation: "Microsoft Sentinel workbooks provide interactive reports built from queries, visualizations, parameters, and links. They visualize data but do not ingest or detect it.",
    references: [{ pathId: "path-7", moduleId: "p7-module-7", reason: "Review querying, visualization, monitoring, and workbook use." }],
  },
  {
    id: "exam-q-16", domainId: "bp-domain-1", domainTitle: "Manage a security operations environment",
    prompt: "A network appliance emits RFC-compliant CEF messages. Which Sentinel ingestion approach is the most direct fit?",
    options: [{ id: "a", text: "CEF via AMA connector through a Linux log forwarder" }, { id: "b", text: "Windows Security Events via AMA" }, { id: "c", text: "Microsoft Graph activity logs" }, { id: "d", text: "Defender for Cloud Apps connector" }],
    correctOptionId: "a", explanation: "CEF devices commonly send messages to a Linux forwarder, where AMA collects and normalizes them for the CommonSecurityLog table.",
    references: [{ pathId: "path-6", moduleId: "p6-module-5", reason: "Review CEF ingestion, forwarders, AMA, and CommonSecurityLog." }],
  },
  {
    id: "exam-q-17", domainId: "bp-domain-1", domainTitle: "Manage a security operations environment",
    prompt: "On-premises Windows hosts cannot each connect directly to Azure, but their selected events must reach Sentinel. Which design should you use?",
    options: [{ id: "a", text: "Windows Event Forwarding to an AMA-enabled collector" }, { id: "b", text: "A Purview Audit search" }, { id: "c", text: "A Defender XDR incident queue" }, { id: "d", text: "A Sentinel watchlist" }],
    correctOptionId: "a", explanation: "WEF consolidates events on a Windows Event Collector. AMA on that collector can then send the chosen events to the configured workspace.",
    references: [{ pathId: "path-6", moduleId: "p6-module-4", reason: "Review Windows Event Forwarding and AMA collection architectures." }],
  },
  {
    id: "exam-q-18", domainId: "bp-domain-1", domainTitle: "Manage a security operations environment",
    prompt: "You must collect Azure subscription-level create, update, and delete operations in Sentinel. Which source should be connected?",
    options: [{ id: "a", text: "Azure Activity" }, { id: "b", text: "DeviceProcessEvents" }, { id: "c", text: "EmailEvents" }, { id: "d", text: "CommonSecurityLog" }],
    correctOptionId: "a", explanation: "Azure Activity records control-plane operations at subscription level. The connector can be deployed consistently with Azure Policy and diagnostic settings.",
    references: [{ pathId: "path-6", moduleId: "p6-module-2", reason: "Review connecting Azure services and activity data to Sentinel." }],
  },
  {
    id: "exam-q-19", domainId: "bp-domain-1", domainTitle: "Manage a security operations environment",
    prompt: "A threat-intelligence platform provides current malicious IP addresses that must be available to analytics rules and hunting. What should you ingest?",
    options: [{ id: "a", text: "Threat indicators" }, { id: "b", text: "Workbook parameters" }, { id: "c", text: "Incident comments" }, { id: "d", text: "Device inventory" }],
    correctOptionId: "a", explanation: "Threat indicators enrich detections and hunting with observable values and context such as confidence, validity, and threat type.",
    references: [{ pathId: "path-6", moduleId: "p6-module-7", reason: "Review threat-intelligence connectors and indicator ingestion." }],
  },
  {
    id: "exam-q-20", domainId: "bp-domain-1", domainTitle: "Manage a security operations environment",
    prompt: "You are designing a custom Log Analytics table for a proprietary security feed. Which requirement is mandatory?",
    options: [{ id: "a", text: "The name uses _CL and the schema includes TimeGenerated" }, { id: "b", text: "Every field is stored as dynamic" }, { id: "c", text: "The table uses the SecurityEvent schema" }, { id: "d", text: "The feed bypasses a DCR" }],
    correctOptionId: "a", explanation: "Custom tables use the _CL suffix and require TimeGenerated. A DCR defines the stream, transformation, destination, and schema contract.",
    references: [{ pathId: "path-6", moduleId: "p6-module-1", reason: "Review connector selection and custom ingestion design." }],
  },
  {
    id: "exam-q-21", domainId: "bp-domain-1", domainTitle: "Manage a security operations environment",
    prompt: "An Advanced Hunting query reliably identifies malicious PowerShell and must run every hour with device actions when matched. What should you create?",
    options: [{ id: "a", text: "A custom detection rule" }, { id: "b", text: "A workbook" }, { id: "c", text: "A device inventory filter" }, { id: "d", text: "A retention policy" }],
    correctOptionId: "a", explanation: "A custom detection operationalizes a validated Advanced Hunting query on a schedule and can generate alerts and supported response actions.",
    references: [{ pathId: "path-2", moduleId: "p2-module-8", reason: "Review custom detections, schedules, alert context, and response actions." }],
  },
  {
    id: "exam-q-22", domainId: "bp-domain-1", domainTitle: "Manage a security operations environment",
    prompt: "A built-in alert repeatedly fires for one documented benign scanner. How should noise be reduced with the lowest risk of hiding attacks?",
    options: [{ id: "a", text: "Create a narrowly scoped alert-tuning rule for stable scanner attributes" }, { id: "b", text: "Disable the alert policy globally" }, { id: "c", text: "Close every incident automatically" }, { id: "d", text: "Exclude the entire subnet from telemetry" }],
    correctOptionId: "a", explanation: "Precise tuning suppresses the known benign condition while retaining coverage elsewhere. Broad suppression or disabled collection can conceal true positives.",
    references: [{ pathId: "path-2", moduleId: "p2-module-8", reason: "Review alert tuning, suppression scope, and detection management." }],
  },
  {
    id: "exam-q-23", domainId: "bp-domain-1", domainTitle: "Manage a security operations environment",
    prompt: "You want to evaluate an attack surface reduction rule's business impact before enforcing it. Which mode should be used first?",
    options: [{ id: "a", text: "Audit" }, { id: "b", text: "Block with no pilot" }, { id: "c", text: "Disabled" }, { id: "d", text: "Device isolation" }],
    correctOptionId: "a", explanation: "Audit mode records what the rule would affect without blocking, allowing validation and exclusion design before controlled enforcement.",
    references: [{ pathId: "path-2", moduleId: "p2-module-3", reason: "Review ASR rule modes, deployment, exclusions, and validation." }],
  },
  {
    id: "exam-q-24", domainId: "bp-domain-1", domainTitle: "Manage a security operations environment",
    prompt: "Automated investigation finds a malicious file but the device group's automation level requires approval. What should the analyst expect?",
    options: [{ id: "a", text: "The remediation action waits for approval in Action center" }, { id: "b", text: "The device is deleted automatically" }, { id: "c", text: "The investigation is converted to a workbook" }, { id: "d", text: "All evidence is suppressed" }],
    correctOptionId: "a", explanation: "Automation levels determine whether remediation is automatic or requires approval. Pending actions are reviewed and approved or rejected in Action center.",
    references: [{ pathId: "path-2", moduleId: "p2-module-7", reason: "Review automated investigation, remediation approval, and Action center." }],
  },
  {
    id: "exam-q-25", domainId: "bp-domain-1", domainTitle: "Manage a security operations environment",
    prompt: "Defender XDR automatically contains a compromised identity and device during an active attack. Which capability performed this coordinated response?",
    options: [{ id: "a", text: "Automatic attack disruption" }, { id: "b", text: "A workbook refresh" }, { id: "c", text: "A watchlist update" }, { id: "d", text: "Data retention" }],
    correctOptionId: "a", explanation: "Automatic attack disruption correlates high-confidence signals across workloads and takes coordinated containment actions to stop attack progression.",
    references: [{ pathId: "path-1", moduleId: "module-2", reason: "Review incident correlation, automated response, and attack disruption." }],
  },
  {
    id: "exam-q-26", domainId: "bp-domain-1", domainTitle: "Manage a security operations environment",
    prompt: "A Sentinel playbook must disable a user without relying on the analyst who triggered it. Which authentication design is preferred?",
    options: [{ id: "a", text: "A managed identity with the required least-privilege permissions" }, { id: "b", text: "The analyst's personal password in the workflow" }, { id: "c", text: "Anonymous access" }, { id: "d", text: "A workbook parameter" }],
    correctOptionId: "a", explanation: "A managed identity avoids embedded user credentials and can be granted only the permissions required by the Logic Apps workflow.",
    references: [{ pathId: "path-7", moduleId: "p7-module-3", reason: "Review playbook triggers, connectors, identities, and permissions." }],
  },
  {
    id: "exam-q-27", domainId: "bp-domain-1", domainTitle: "Manage a security operations environment",
    prompt: "SOC optimization reports billable data in a table that has no detections or investigation use. What should you do before stopping ingestion?",
    options: [{ id: "a", text: "Validate security, compliance, retention, and downstream dependencies" }, { id: "b", text: "Delete the table immediately" }, { id: "c", text: "Close all open incidents" }, { id: "d", text: "Disable Sentinel" }],
    correctOptionId: "a", explanation: "Optimization recommendations support a decision; they are not automatic instructions. Validate value, requirements, dependencies, and cost before implementing them.",
    references: [{ pathId: "path-5", moduleId: "p5-module-2", reason: "Review workspace planning, data value, and operational dependencies." }],
  },
  {
    id: "exam-q-28", domainId: "bp-domain-1", domainTitle: "Manage a security operations environment",
    prompt: "Sentinel identifies behavior that deviates from a learned baseline without a static threshold. What detection concept is being used?",
    options: [{ id: "a", text: "Anomaly detection" }, { id: "b", text: "A watchlist export" }, { id: "c", text: "Manual incident assignment" }, { id: "d", text: "Table retention" }],
    correctOptionId: "a", explanation: "Anomaly detections use models or behavioral baselines to surface deviations that fixed conditions can miss.",
    references: [{ pathId: "path-7", moduleId: "p7-module-5", reason: "Review behavioral analytics, baselines, and anomaly-driven investigation." }],
  },
  {
    id: "exam-q-29", domainId: "bp-domain-1", domainTitle: "Manage a security operations environment",
    prompt: "You map enabled detections to MITRE ATT&CK and find no coverage for a technique relevant to your threat model. What does the gap indicate?",
    options: [{ id: "a", text: "A candidate area for new telemetry or detection logic" }, { id: "b", text: "Proof the technique cannot occur" }, { id: "c", text: "A reason to disable adjacent detections" }, { id: "d", text: "A failed data-retention policy" }],
    correctOptionId: "a", explanation: "MITRE mapping helps assess detection coverage. A relevant gap should drive validation of data sources, analytics, and acceptable risk, not assumptions about impossibility.",
    references: [{ pathId: "path-7", moduleId: "p7-module-1", reason: "Review detection engineering and MITRE ATT&CK coverage." }],
  },
  {
    id: "exam-q-30", domainId: "bp-domain-2", domainTitle: "Respond to security incidents",
    prompt: "A malicious message reached multiple mailboxes. After confirming the campaign, which action most directly removes the delivered messages?",
    options: [{ id: "a", text: "Soft delete or hard delete through Explorer remediation" }, { id: "b", text: "Isolate every endpoint" }, { id: "c", text: "Change Sentinel retention" }, { id: "d", text: "Create a workbook" }],
    correctOptionId: "a", explanation: "Defender for Office 365 remediation can move or delete identified messages after investigation. Scope and permissions should be verified before submission.",
    references: [{ pathId: "path-1", moduleId: "module-3", reason: "Review threat remediation across Microsoft Defender workloads." }],
  },
  {
    id: "exam-q-31", domainId: "bp-domain-2", domainTitle: "Respond to security incidents",
    prompt: "Defender for Cloud reports suspicious execution on an Azure VM. What should you review first to establish workload context and scope?",
    options: [{ id: "a", text: "The alert evidence, affected resource, recommendations, and related attack path" }, { id: "b", text: "Only the subscription name" }, { id: "c", text: "A random user mailbox" }, { id: "d", text: "The SC-200 score report" }],
    correctOptionId: "a", explanation: "Cloud alert investigation combines evidence with asset context, protection coverage, recommendations, and relationships that may expose additional resources.",
    references: [{ pathId: "path-3", moduleId: "p3-module-6", reason: "Review investigation and remediation of Defender for Cloud alerts." }],
  },
  {
    id: "exam-q-32", domainId: "bp-domain-2", domainTitle: "Respond to security incidents",
    prompt: "A user granted a suspicious OAuth app high-impact permissions. Which response best addresses persistence?",
    options: [{ id: "a", text: "Revoke the app's grants, disable or remove it, revoke sessions, and investigate activity" }, { id: "b", text: "Rename the application" }, { id: "c", text: "Add the app name to a workbook" }, { id: "d", text: "Dismiss the alert without review" }],
    correctOptionId: "a", explanation: "Consent-based persistence requires removing the malicious authorization and app access, containing affected identities, and investigating what the app accessed.",
    references: [{ pathId: "path-1", moduleId: "module-6", reason: "Review risky cloud applications, OAuth activity, and remediation." }],
  },
  {
    id: "exam-q-33", domainId: "bp-domain-2", domainTitle: "Respond to security incidents",
    prompt: "Defender for Identity raises a suspected pass-the-ticket alert. Which evidence is most useful for validating lateral movement?",
    options: [{ id: "a", text: "Identity timeline, source device, destination resources, and related authentications" }, { id: "b", text: "Workbook color settings" }, { id: "c", text: "Data Lake cost only" }, { id: "d", text: "The user's email signature" }],
    correctOptionId: "a", explanation: "Identity alerts must be correlated with involved devices, accounts, authentication activity, and subsequent resource access to validate movement and scope.",
    references: [{ pathId: "path-1", moduleId: "module-5", reason: "Review Defender for Identity alerts, entity timelines, and remediation." }],
  },
  {
    id: "exam-q-34", domainId: "bp-domain-2", domainTitle: "Respond to security incidents",
    prompt: "During a Sentinel investigation, you find a query result that must be preserved and associated with the incident. What should you create?",
    options: [{ id: "a", text: "A bookmark linked to the incident" }, { id: "b", text: "A new data connector" }, { id: "c", text: "A table-retention exception" }, { id: "d", text: "A device group" }],
    correctOptionId: "a", explanation: "Bookmarks preserve selected query results, notes, entities, and investigation context and can be added to incidents.",
    references: [{ pathId: "path-7", moduleId: "p7-module-4", reason: "Review Sentinel incident investigation, evidence, entities, and bookmarks." }],
  },
  {
    id: "exam-q-35", domainId: "bp-domain-2", domainTitle: "Respond to security incidents",
    prompt: "Security Copilot summarizes an incident and recommends isolating three devices. What must the analyst do before approving the action?",
    options: [{ id: "a", text: "Validate the recommendation against alerts, entities, timelines, and business context" }, { id: "b", text: "Assume all generated output is authoritative" }, { id: "c", text: "Delete the source evidence" }, { id: "d", text: "Disable audit logging" }],
    correctOptionId: "a", explanation: "AI accelerates investigation but can be incomplete or wrong. Consequential response actions require evidence validation and human judgment.",
    references: [{ pathId: "path-1", moduleId: "module-2", reason: "Review evidence-based incident investigation and coordinated response." }],
  },
  {
    id: "exam-q-36", domainId: "bp-domain-2", domainTitle: "Respond to security incidents",
    prompt: "A blast-radius graph shows a possible path from a compromised identity to a critical server. How should the path be treated?",
    options: [{ id: "a", text: "As an investigative lead that requires corroboration" }, { id: "b", text: "As proof every edge was used" }, { id: "c", text: "As a reason to erase the incident" }, { id: "d", text: "As a replacement for event evidence" }],
    correctOptionId: "a", explanation: "Blast-radius paths model potential reach. Confirm important relationships with entity data, alerts, timelines, and hunting before concluding attacker activity.",
    references: [{ pathId: "path-1", moduleId: "module-2", reason: "Review complex incident scope, entity pivots, and attack progression." }],
  },
  {
    id: "exam-q-37", domainId: "bp-domain-2", domainTitle: "Respond to security incidents",
    prompt: "You need to determine which process created a suspicious file and what network connections followed on one endpoint. Where should you pivot first?",
    options: [{ id: "a", text: "The device timeline" }, { id: "b", text: "The Sentinel role assignment page" }, { id: "c", text: "A Purview retention label" }, { id: "d", text: "The workbook gallery" }],
    correctOptionId: "a", explanation: "The device timeline correlates endpoint events chronologically and supports pivots across processes, files, network activity, users, and alerts.",
    references: [{ pathId: "path-2", moduleId: "p2-module-4", reason: "Review device timeline investigation and event pivots." }],
  },
  {
    id: "exam-q-38", domainId: "bp-domain-2", domainTitle: "Respond to security incidents",
    prompt: "An analyst needs an interactive shell on an isolated Windows device to collect a script output. Which MDE capability should be used?",
    options: [{ id: "a", text: "Live response" }, { id: "b", text: "Email Explorer" }, { id: "c", text: "Sentinel workbook" }, { id: "d", text: "Purview Content Search" }],
    correctOptionId: "a", explanation: "Live response provides a controlled remote shell for approved investigation and remediation commands on supported devices.",
    references: [{ pathId: "path-2", moduleId: "p2-module-5", reason: "Review live response prerequisites, commands, and device actions." }],
  },
  {
    id: "exam-q-39", domainId: "bp-domain-2", domainTitle: "Respond to security incidents",
    prompt: "A suspicious file appears across several devices. Which Defender experience helps review its prevalence, observed behavior, and associated alerts?",
    options: [{ id: "a", text: "The file entity page" }, { id: "b", text: "The Azure Activity connector" }, { id: "c", text: "A DCR association" }, { id: "d", text: "A retention policy" }],
    correctOptionId: "a", explanation: "File entity investigation centralizes prevalence, devices, alerts, certificates, behavior, and available response actions for the artifact.",
    references: [{ pathId: "path-2", moduleId: "p2-module-6", reason: "Review evidence and entity investigation for files, IPs, users, and devices." }],
  },
  {
    id: "exam-q-40", domainId: "bp-domain-2", domainTitle: "Respond to security incidents",
    prompt: "Automatic attack disruption contained an account. What should happen before the incident is closed?",
    options: [{ id: "a", text: "Verify containment, investigate root cause and scope, remediate, and document results" }, { id: "b", text: "Assume containment equals eradication" }, { id: "c", text: "Remove all incident evidence" }, { id: "d", text: "Disable future disruption" }],
    correctOptionId: "a", explanation: "Automated containment stops progression but does not replace investigation, eradication, recovery validation, classification, and documentation.",
    references: [{ pathId: "path-1", moduleId: "module-3", reason: "Review remediation, recovery validation, and incident closure." }],
  },
  {
    id: "exam-q-41", domainId: "bp-domain-2", domainTitle: "Respond to security incidents",
    prompt: "A Purview DLP alert reports sensitive data copied to an unmanaged cloud destination. What is the best first investigation approach?",
    options: [{ id: "a", text: "Review the alert, matched policy, user, activity, content context, and related events" }, { id: "b", text: "Delete the DLP policy immediately" }, { id: "c", text: "Isolate every corporate device" }, { id: "d", text: "Ignore the policy match" }],
    correctOptionId: "a", explanation: "DLP investigation begins with the alert and policy match, then validates the user, destination, content sensitivity, activity sequence, and broader risk context.",
    references: [{ pathId: "path-9", moduleId: "p9-module-1", reason: "Review DLP alert investigation, context, and response." }],
  },
  {
    id: "exam-q-42", domainId: "bp-domain-2", domainTitle: "Respond to security incidents",
    prompt: "An insider risk alert contains several indicators about one user. What should determine whether escalation is justified?",
    options: [{ id: "a", text: "Correlated activity, sequence, context, policy scope, and privacy-governed evidence" }, { id: "b", text: "One isolated indicator alone" }, { id: "c", text: "The user's job title only" }, { id: "d", text: "The number of workbooks" }],
    correctOptionId: "a", explanation: "Insider risk decisions require contextual, correlated evidence and governed handling rather than conclusions from a single activity.",
    references: [{ pathId: "path-9", moduleId: "p9-module-2", reason: "Review insider risk alerts, user activity, governance, and escalation." }],
  },
  {
    id: "exam-q-43", domainId: "bp-domain-2", domainTitle: "Respond to security incidents",
    prompt: "Legal investigators need messages and documents matching keywords, custodians, and dates for a case. Which capability best fits?",
    options: [{ id: "a", text: "Microsoft Purview eDiscovery Content Search" }, { id: "b", text: "MDE device isolation" }, { id: "c", text: "A Sentinel NRT rule" }, { id: "d", text: "An ASR rule" }],
    correctOptionId: "a", explanation: "eDiscovery Content Search supports scoped, reviewable searches across Microsoft 365 content using locations, custodians, keywords, and conditions.",
    references: [{ pathId: "path-9", moduleId: "p9-module-4", reason: "Review eDiscovery cases, search scope, statistics, preview, and export." }],
  },
  {
    id: "exam-q-44", domainId: "bp-domain-2", domainTitle: "Respond to security incidents",
    prompt: "You suspect a service principal is enumerating Microsoft Graph resources. Which table provides request URI, method, status, AppId, and caller context?",
    options: [{ id: "a", text: "MicrosoftGraphActivityLogs" }, { id: "b", text: "DeviceFileEvents" }, { id: "c", text: "CommonSecurityLog" }, { id: "d", text: "EmailAttachmentInfo" }],
    correctOptionId: "a", explanation: "MicrosoftGraphActivityLogs records Microsoft Graph HTTP requests and supports correlation by application, service principal, user, IP, URI, status, and RequestId.",
    references: [{ pathId: "path-5", moduleId: "p5-module-3", reason: "Review querying Sentinel logs and correlating activity records." }],
  },
  {
    id: "exam-q-45", domainId: "bp-domain-3", domainTitle: "Perform threat hunting",
    prompt: "You need process creation events, command lines, parent processes, hashes, and initiating accounts from Defender XDR. Which table should you query first?",
    options: [{ id: "a", text: "DeviceProcessEvents" }, { id: "b", text: "EmailEvents" }, { id: "c", text: "IdentityDirectoryEvents" }, { id: "d", text: "CloudAppEvents" }],
    correctOptionId: "a", explanation: "DeviceProcessEvents contains endpoint process creation and related execution context, making it the primary table for process-chain hunting.",
    references: [{ pathId: "path-4", moduleId: "p4-module-1", reason: "Review KQL table selection, filtering, and projection." }],
  },
  {
    id: "exam-q-46", domainId: "bp-domain-3", domainTitle: "Perform threat hunting",
    prompt: "A hunting query scans a large table and runs slowly. Which change usually reduces scanned data earliest?",
    options: [{ id: "a", text: "Apply a selective TimeGenerated filter near the start" }, { id: "b", text: "Sort every row before filtering" }, { id: "c", text: "Add unused columns" }, { id: "d", text: "Convert all values to strings" }],
    correctOptionId: "a", explanation: "Early time and selective filters reduce the dataset processed by later operators, improving performance and resource use.",
    references: [{ pathId: "path-4", moduleId: "p4-module-4", reason: "Review efficient KQL filtering and query construction." }],
  },
  {
    id: "exam-q-47", domainId: "bp-domain-3", domainTitle: "Perform threat hunting",
    prompt: "A hunting graph displays a possible shortest path from a user to a critical asset. What should you do next?",
    options: [{ id: "a", text: "Inspect nodes and edges, then corroborate relationships with underlying events" }, { id: "b", text: "Declare compromise from the visualization alone" }, { id: "c", text: "Delete the source entities" }, { id: "d", text: "Disable data collection" }],
    correctOptionId: "a", explanation: "Graph paths expose relationships and potential reach. Evidence from entity pages, alerts, timelines, and Advanced Hunting is needed to validate actual activity.",
    references: [{ pathId: "path-8", moduleId: "p8-module-2", reason: "Review hypothesis-driven hunting, pivots, and evidence validation." }],
  },
  {
    id: "exam-q-48", domainId: "bp-domain-3", domainTitle: "Perform threat hunting",
    prompt: "You need to traverse custom node and edge relationships in Microsoft Sentinel Graph. Which query language is designed for that model?",
    options: [{ id: "a", text: "Graph Query Language (GQL)" }, { id: "b", text: "XPath" }, { id: "c", text: "DAX" }, { id: "d", text: "PowerShell remoting" }],
    correctOptionId: "a", explanation: "Sentinel Graph uses nodes, directed edges, properties, and paths that can be explored with GQL after inspecting the graph schema.",
    references: [{ pathId: "path-8", moduleId: "p8-module-2", reason: "Review relationship-based hunting and graph investigation concepts." }],
  },
  {
    id: "exam-q-49", domainId: "bp-domain-3", domainTitle: "Perform threat hunting",
    prompt: "A long-running historical join must execute nightly against Data Lake data and write enriched results to a destination table. What should you use?",
    options: [{ id: "a", text: "A scheduled KQL job" }, { id: "b", text: "An NRT analytics rule" }, { id: "c", text: "A device isolation action" }, { id: "d", text: "An email notification" }],
    correctOptionId: "a", explanation: "KQL jobs run asynchronous one-time or scheduled queries against Data Lake and federated data and can write results to compatible destination tables.",
    references: [{ pathId: "path-8", moduleId: "p8-module-3", reason: "Review historical search workloads and asynchronous query patterns." }],
  },
  {
    id: "exam-q-50", domainId: "bp-domain-3", domainTitle: "Perform threat hunting",
    prompt: "An AI client uses Sentinel MCP tools to answer a hunting question. Which validation principle remains mandatory?",
    options: [{ id: "a", text: "Verify workspace, tables, time range, permissions, tool output, and source evidence" }, { id: "b", text: "Treat natural-language output as proof" }, { id: "c", text: "Assume MCP bypasses RBAC" }, { id: "d", text: "Discard the generated queries" }],
    correctOptionId: "a", explanation: "MCP tools operate within identity and data scope, and model output can be incomplete. Preserve and validate queries, sources, entities, time ranges, and findings before action.",
    references: [{ pathId: "path-8", moduleId: "p8-module-4", reason: "Review governed notebook and AI-assisted hunting workflows." }],
  },
];
