import type { PracticeLabScenario } from "@/lib/types";

export const practiceLabs: PracticeLabScenario[] = [
  {
    id: "practice-lab-1",
    title: "Investigate a consent-phishing and endpoint compromise",
    subtitle: "Correlate identity, cloud app, email, and endpoint evidence into one defensible incident response.",
    difficulty: "Intermediate",
    estimatedMinutes: 30,
    primaryDomain: "Respond to security incidents",
    products: ["Microsoft Defender XDR", "Microsoft Entra ID", "Defender for Cloud Apps", "Defender for Endpoint"],
    briefing: "A finance analyst reports an unexpected consent prompt after opening a supplier invoice email. Microsoft Defender XDR correlates alerts involving the user, an OAuth application, mailbox activity, and suspicious PowerShell execution on the analyst's device.",
    mission: "Determine the attack scope, contain the affected assets, preserve useful evidence, and close the incident with the correct classification.",
    stages: [
      {
        id: "stage-1",
        number: 1,
        title: "Triage the incident",
        objective: "Establish ownership, priority, and the first investigation path without losing the correlated attack context.",
        briefing: "A new high-severity incident appears in the Defender portal. You are the first analyst assigned to review it.",
        evidence: [
          {
            id: "incident-snapshot",
            title: "Incident queue snapshot",
            category: "incident",
            facts: [
              "Severity: High; status: New; owner: Unassigned.",
              "Four correlated alerts from Defender for Office 365, Microsoft Entra ID, Defender for Cloud Apps, and Defender for Endpoint.",
              "Affected user: alex.wilber@contoso.com; affected device: FIN-LT-042.",
              "Related OAuth application: Contoso Document Viewer.",
            ],
          },
        ],
        decision: {
          prompt: "What is the best initial action?",
          options: [
            {
              id: "assign-review-story",
              text: "Assign the incident, set it to Active, validate its severity, and review the complete attack story and affected entities.",
              rating: "recommended",
              feedback: "This preserves the correlated context, establishes accountability, and lets you identify any evidence that requires immediate containment.",
            },
            {
              id: "isolate-first",
              text: "Isolate FIN-LT-042 immediately and review the identity, app, and email evidence afterward.",
              rating: "acceptable",
              feedback: "Urgent isolation can be justified when active execution is likely, but it addresses only the device and should not replace rapid cross-domain triage.",
            },
            {
              id: "separate-alerts",
              text: "Investigate each alert separately without using the incident correlation.",
              rating: "risky",
              feedback: "This fragments the attack story and increases the chance of missing relationships among the user, application, mailbox, and device.",
            },
            {
              id: "close-user-report",
              text: "Close the incident because the original email was reported by the user.",
              rating: "risky",
              feedback: "A user report is a starting signal, not proof that the associated activity is harmless.",
            },
          ],
        },
        outcome: [
          "The incident is assigned to you and moved to Active.",
          "The attack story shows email delivery, OAuth consent, cloud activity, and endpoint execution in one sequence.",
        ],
        hint: "Start with the incident as the correlated attack story. Establish ownership and identify the entities and alerts that could require immediate action.",
        takeaway: "Initial triage should establish ownership, priority, scope, and the evidence requiring immediate containment.",
        references: [
          { pathId: "path-1", moduleId: "module-2", reason: "Review incident assignment, severity, attack stories, affected assets, classification, and the Defender XDR investigation lifecycle." },
        ],
      },
      {
        id: "stage-2",
        number: 2,
        title: "Analyze the evidence",
        objective: "Distinguish isolated suspicious events from a supported multi-domain compromise conclusion.",
        briefing: "The incident graph connects the reported message, the user, the OAuth application, the mailbox, and FIN-LT-042. Review each evidence source before deciding what is compromised.",
        evidence: [
          {
            id: "email-evidence",
            title: "Email evidence",
            category: "email",
            facts: [
              "Display name: Fabrikam Accounts; sender domain: fabrikam-payments.co.",
              "Subject: Updated Q3 supplier statement.",
              "The user clicked an embedded URL at 08:47 UTC.",
              "The sender domain was registered recently and does not match the known supplier domain.",
            ],
          },
          {
            id: "oauth-evidence",
            title: "OAuth consent evidence",
            category: "identity",
            facts: [
              "Application: Contoso Document Viewer; publisher: Unverified.",
              "Delegated permissions: Mail.ReadWrite, Files.Read.All, and offline_access.",
              "Consent was granted at 08:49 UTC, two minutes after the URL click.",
              "The application is rare in the tenant and has no approved business owner.",
            ],
          },
          {
            id: "cloud-evidence",
            title: "Cloud activity",
            category: "cloud",
            facts: [
              "The application accessed the user's mailbox and read multiple messages.",
              "It downloaded files from a SharePoint site.",
              "Activity continued after the original browser session ended.",
              "Requests originated from an IP address not previously associated with the user.",
            ],
          },
          {
            id: "device-evidence",
            title: "Device timeline",
            category: "device",
            facts: [
              "msedge.exe launched PowerShell shortly after the phishing URL click.",
              "PowerShell downloaded sync-update.ps1 and created a scheduled task named Document Sync Update.",
              "The script contacted the same unfamiliar external IP seen in the cloud activity.",
              "Defender detected the script as suspicious but did not confirm that every action was remediated.",
            ],
          },
        ],
        decision: {
          prompt: "Which conclusion is best supported by the evidence?",
          options: [
            {
              id: "multi-domain-compromise",
              text: "The user granted a risky OAuth application access and the device executed a related payload; treat the user, application, mailbox, and device as potentially compromised.",
              rating: "recommended",
              feedback: "The timing, shared infrastructure, permissions, cloud access, and device execution support a connected multi-domain compromise hypothesis.",
            },
            {
              id: "endpoint-confirmed-app-pending",
              text: "Endpoint compromise is confirmed, but continue validating the OAuth application's behavior before declaring it malicious.",
              rating: "acceptable",
              feedback: "This is defensible caution, but the unverified app, high-impact permissions, rare tenant use, and post-consent activity already create a strong malicious-app assessment.",
            },
            {
              id: "device-only",
              text: "The incident affects only FIN-LT-042 because PowerShell is the only executable evidence.",
              rating: "risky",
              feedback: "This ignores confirmed application access to mailbox and SharePoint data after the consent grant.",
            },
            {
              id: "consent-equals-trust",
              text: "The OAuth application is trustworthy because the user granted consent interactively.",
              rating: "risky",
              feedback: "User consent does not establish publisher trust, business approval, or safe behavior.",
            },
          ],
        },
        outcome: [
          "The incident hypothesis is upgraded to a likely consent-phishing campaign with related endpoint execution.",
          "The user, OAuth application, mailbox, device, phishing URL, script, scheduled task, and external IP become investigation pivots.",
        ],
        hint: "Correlate timing, shared infrastructure, requested permissions, post-consent activity, and endpoint process lineage. Avoid treating user consent as a trust signal.",
        takeaway: "A supported conclusion should explain all material evidence across domains, not only the most visible alert.",
        references: [
          { pathId: "path-1", moduleId: "module-2", reason: "Review how Defender XDR correlates alerts, evidence, and entities into a unified incident." },
          { pathId: "path-1", moduleId: "module-6", reason: "Review OAuth application behavior, risky cloud activity, and investigation with Defender for Cloud Apps." },
          { pathId: "path-2", moduleId: "p2-module-4", reason: "Review device timelines and the endpoint evidence used to validate a compromise." },
        ],
      },
      {
        id: "stage-3",
        number: 3,
        title: "Determine the scope",
        objective: "Use shared indicators and entities to find related users, devices, applications, messages, and cloud activity.",
        briefing: "The original incident confirms suspicious activity for one user and one device, but it does not yet establish whether the campaign reached other assets.",
        evidence: [
          {
            id: "known-pivots",
            title: "Known investigation pivots",
            category: "hunting",
            facts: [
              "OAuth application ID and consent timestamp.",
              "Phishing URL, sender domain, and message subject.",
              "sync-update.ps1 hash, PowerShell command line, and scheduled task name.",
              "External IP shared by the cloud application and endpoint script.",
            ],
          },
        ],
        decision: {
          prompt: "What is the strongest next investigation plan?",
          options: [
            {
              id: "tenant-wide-pivots",
              text: "Hunt tenant-wide using the application ID, consent activity, URL, sender domain, file hash, script name, scheduled task, and external IP.",
              rating: "recommended",
              feedback: "This tests the campaign hypothesis across identity, email, cloud, and endpoint data and can reveal affected assets outside the original incident.",
            },
            {
              id: "endpoint-pivots-only",
              text: "Search all endpoints for the PowerShell command and file hash, but postpone cloud-application analysis.",
              rating: "acceptable",
              feedback: "This can find additional device execution, but it leaves the persistent OAuth access path and other consenting users unscoped.",
            },
            {
              id: "mailbox-only",
              text: "Review only Alex Wilber's mailbox because that user generated the incident.",
              rating: "risky",
              feedback: "Campaign scope cannot be established from the originally affected mailbox alone.",
            },
            {
              id: "reset-and-stop",
              text: "Reset Alex Wilber's password and stop the investigation.",
              rating: "risky",
              feedback: "A password reset neither scopes the campaign nor necessarily removes application grants and active access paths.",
            },
          ],
        },
        outcome: [
          "Three users granted consent to the same application, and two users clicked the phishing URL.",
          "The PowerShell payload executed on one device only.",
          "The application accessed two mailboxes and downloaded files from one SharePoint site.",
          "No additional devices show the scheduled task or script hash during the selected time window.",
        ],
        hint: "Use every stable indicator across the relevant telemetry. Scope the cloud and endpoint paths independently, then correlate the results.",
        takeaway: "The original incident can represent only one part of a campaign; scope is established through deliberate cross-domain pivots.",
        references: [
          { pathId: "path-8", moduleId: "p8-module-2", reason: "Review hypothesis-driven hunting, entity pivots, bookmarks, and investigation across related activity." },
          { pathId: "path-4", moduleId: "p4-module-3", reason: "Review multi-table KQL techniques for correlating indicators across different telemetry sources." },
        ],
      },
      {
        id: "stage-4",
        number: 4,
        title: "Contain and remediate",
        objective: "Choose coordinated actions that stop cloud and endpoint access while preserving useful evidence.",
        briefing: "The campaign affected three users, two mailboxes, one SharePoint site, and one endpoint. The OAuth application still has delegated access, and FIN-LT-042 remains online.",
        evidence: [
          {
            id: "response-readiness",
            title: "Response readiness",
            category: "incident",
            facts: [
              "The security team can disable the enterprise application and revoke its permissions.",
              "Identity administrators can revoke user sessions and reset credentials.",
              "FIN-LT-042 is reachable by Defender for Endpoint and supports isolation and investigation-package collection.",
              "Defender for Office 365 can locate and purge the phishing message from affected mailboxes.",
            ],
          },
        ],
        decision: {
          prompt: "Which response plan best addresses the confirmed scope?",
          options: [
            {
              id: "coordinated-response",
              text: "Disable the OAuth app, revoke its permissions, revoke affected sessions, reset compromised credentials, isolate and collect evidence from the device, purge the message, block indicators, and verify each action.",
              rating: "recommended",
              feedback: "This closes the cloud, identity, email, and endpoint access paths while retaining evidence and requiring verification of the response actions.",
            },
            {
              id: "urgent-containment-first",
              text: "Immediately isolate the device and revoke user sessions, then complete application, email, and credential remediation.",
              rating: "acceptable",
              feedback: "This is a defensible urgent sequence if the remaining actions are assigned and completed without delay; the app grant must not be forgotten.",
            },
            {
              id: "passwords-only",
              text: "Reset the affected users' passwords without revoking the application or active sessions.",
              rating: "risky",
              feedback: "Password resets alone do not reliably eliminate every existing token or the malicious application's permissions.",
            },
            {
              id: "wipe-first",
              text: "Wipe FIN-LT-042 immediately before collecting any investigation evidence.",
              rating: "risky",
              feedback: "Destructive remediation can remove evidence needed to establish persistence, payload behavior, and root cause.",
            },
            {
              id: "email-only",
              text: "Delete the phishing email and close the incident.",
              rating: "risky",
              feedback: "Deleting the initial message does not remove the OAuth grant, active sessions, accessed data, or endpoint persistence.",
            },
          ],
        },
        outcome: [
          "The OAuth application is disabled and its delegated permissions are revoked.",
          "Sessions are revoked and credentials reset for the three affected users.",
          "FIN-LT-042 is isolated while retaining Defender connectivity, and an investigation package is collected before remediation.",
          "The phishing messages are purged and the confirmed indicators are blocked.",
        ],
        hint: "Map one response action to every confirmed access path. Preserve evidence before destructive remediation and verify actions in the relevant action center or audit record.",
        takeaway: "Effective containment is coordinated: device isolation alone does not stop cloud access, and a password reset alone does not remove an application grant.",
        references: [
          { pathId: "path-2", moduleId: "p2-module-5", reason: "Review device isolation, investigation packages, remediation actions, and action verification." },
          { pathId: "path-1", moduleId: "module-6", reason: "Review cloud application containment, permission revocation, session controls, and OAuth remediation." },
          { pathId: "path-1", moduleId: "module-3", reason: "Review email investigation and remediation actions for phishing messages and malicious content." },
        ],
      },
      {
        id: "stage-5",
        number: 5,
        title: "Validate and close",
        objective: "Confirm response outcomes and resolve the incident with a defensible classification and investigation record.",
        briefing: "The planned response actions have completed. Before closing the incident, verify their results and determine the correct classification.",
        evidence: [
          {
            id: "validation-status",
            title: "Validation status",
            category: "incident",
            facts: [
              "The OAuth application is disabled and no longer has delegated permissions.",
              "Session revocation and password resets completed for all three affected users.",
              "The scheduled task and payload were removed from FIN-LT-042 after evidence collection.",
              "The phishing messages were purged, and no new related activity appeared during the validation window.",
            ],
          },
        ],
        decision: {
          prompt: "How should the incident be resolved?",
          options: [
            {
              id: "true-positive-close",
              text: "Classify it as a true positive with malicious activity, document the attack chain, affected entities, evidence, response actions, and monitoring requirements, then close it.",
              rating: "recommended",
              feedback: "This classification matches the confirmed malicious consent, unauthorized cloud access, and endpoint execution, and it preserves an actionable investigation record.",
            },
            {
              id: "monitor-active",
              text: "Keep the incident Active for an additional monitoring period with an owner and a documented reason.",
              rating: "acceptable",
              feedback: "Additional observation can be justified by organizational policy, provided ownership, exit criteria, and the reason for delaying closure are explicit.",
            },
            {
              id: "false-positive-consent",
              text: "Classify it as a false positive because the users granted consent themselves.",
              rating: "risky",
              feedback: "The consent was obtained through phishing and followed by unauthorized access and endpoint execution; user interaction does not make the activity benign.",
            },
            {
              id: "close-no-record",
              text: "Close the incident without classification or investigation comments because remediation succeeded.",
              rating: "risky",
              feedback: "Missing classification and documentation weakens metrics, handoff, lessons learned, and future detection tuning.",
            },
          ],
        },
        outcome: [
          "The incident is recorded as a true positive with malicious activity.",
          "The final record includes the timeline, root cause, affected users and resources, indicators, evidence-preservation steps, response actions, and validation results.",
        ],
        hint: "Base closure on verified response outcomes and the evidence-supported nature of the activity, not merely on whether the alerting condition stopped.",
        takeaway: "Accurate classification and documentation complete the response lifecycle and improve future investigations, metrics, and tuning.",
        references: [
          { pathId: "path-1", moduleId: "module-2", reason: "Review incident validation, true-positive classification, resolution, and investigation documentation." },
          { pathId: "path-7", moduleId: "p7-module-4", reason: "Review incident ownership, status, evidence, response tracking, and closure in Microsoft Sentinel." },
        ],
      },
    ],
    debrief: {
      title: "Campaign contained across four security domains",
      summary: "The phishing message initiated two related compromise paths: malicious OAuth consent and endpoint code execution. Device isolation alone would not have stopped cloud access, and a password reset alone would not have removed the application grant. Effective response required coordinated identity, application, email, and endpoint actions followed by verification.",
      keyLessons: [
        "Use the correlated incident to reconstruct the attack before fragmenting work by product.",
        "Treat consent as an event to investigate, not as proof that an OAuth application is trustworthy.",
        "Scope campaigns with shared entity and indicator pivots across every relevant telemetry source.",
        "Map containment to each active access path and preserve evidence before destructive remediation.",
        "Close only after verifying actions and recording an evidence-backed classification.",
      ],
    },
  },
  {
    id: "practice-lab-2",
    title: "Investigate credential abuse and Azure persistence with Microsoft Sentinel",
    subtitle: "Correlate sign-in, audit, and Azure activity to validate a privileged cloud compromise and coordinate the response.",
    difficulty: "Intermediate",
    estimatedMinutes: 35,
    primaryDomain: "Manage a security operations environment",
    products: ["Microsoft Sentinel", "Microsoft Entra ID", "Azure Activity Log", "Logic Apps"],
    briefing: "Microsoft Sentinel creates a high-severity incident after a successful sign-in from an unfamiliar network is followed by a privileged role assignment and a new application credential. The operations target a production subscription and occur outside the administrator's normal working pattern.",
    mission: "Validate whether the activity is malicious, reconstruct the cloud attack sequence, determine the affected identities and resources, contain every access path, and improve the detection after closure.",
    stages: [
      {
        id: "sentinel-stage-1",
        number: 1,
        title: "Triage the Sentinel incident",
        objective: "Establish ownership and validate the detection context before making a compromise determination.",
        briefing: "The incident was generated by a scheduled analytics rule named Privileged change after anomalous sign-in and contains account, IP address, cloud application, and Azure resource entities.",
        evidence: [
          {
            id: "sentinel-incident-summary",
            title: "Incident and analytics rule summary",
            category: "incident",
            facts: [
              "Severity: High; status: New; tactics: Initial Access and Persistence.",
              "The rule runs every 10 minutes with a 30-minute lookup window and groups matching alerts by account.",
              "Mapped entities include jordan.lee@contoso.com, IP 198.51.100.77, application Azure Portal, and subscription PROD-01.",
              "The incident contains three alerts created within a 14-minute period.",
            ],
          },
        ],
        decision: {
          prompt: "What is the strongest first action?",
          options: [
            {
              id: "sentinel-triage-correlated",
              text: "Assign the incident, set it to Active, review the analytics rule logic and entity mappings, then inspect the complete alert timeline and related entities.",
              rating: "recommended",
              feedback: "This preserves the correlated context, establishes accountability, and verifies what the detection actually proves before response actions begin.",
            },
            {
              id: "sentinel-triage-disable",
              text: "Disable Jordan Lee's account immediately, without first checking whether the operations came from an approved change or automation identity.",
              rating: "acceptable",
              feedback: "Rapid containment may be justified when risk is imminent, but acting before basic validation can disrupt legitimate administration and obscure the original access path.",
            },
            {
              id: "sentinel-triage-vpn",
              text: "Close the incident because unfamiliar locations are commonly caused by corporate VPN gateways.",
              rating: "risky",
              feedback: "A location anomaly alone can be benign, but the correlated privileged changes and application credential require investigation.",
            },
            {
              id: "sentinel-triage-alerts",
              text: "Open each alert in a separate browser tab and investigate them without using the incident entities or timeline.",
              rating: "risky",
              feedback: "Fragmenting the investigation makes it harder to see the sequence connecting authentication, privilege, and persistence.",
            },
          ],
        },
        outcome: [
          "The incident is assigned, moved to Active, and confirmed to contain three logically related alerts.",
          "The rule query and entity mappings correctly connect the account, source IP, application, and Azure subscription.",
        ],
        hint: "First determine why the analytics rule grouped these alerts and which entities can be used as investigation pivots.",
        takeaway: "Sentinel incident triage begins with ownership, detection validation, entity review, and preservation of the correlated timeline.",
        references: [
          { pathId: "path-7", moduleId: "p7-module-4", reason: "Review Sentinel incident evidence, entities, ownership, status, investigation, and closure." },
          { pathId: "path-7", moduleId: "p7-module-1", reason: "Review scheduled analytics rules, query scheduling, alert grouping, and entity mappings." },
        ],
      },
      {
        id: "sentinel-stage-2",
        number: 2,
        title: "Reconstruct the cloud activity",
        objective: "Correlate authentication, directory audit, and Azure control-plane records into an evidence-supported sequence.",
        briefing: "The incident shows suspicious operations, but you must validate their order, caller, target, and authentication context across multiple tables.",
        evidence: [
          {
            id: "sentinel-signin-evidence",
            title: "SigninLogs findings",
            category: "identity",
            facts: [
              "Jordan Lee successfully signed in from 198.51.100.77 using Azure Portal at 02:13 UTC.",
              "The location and autonomous system are new for the user; device detail is empty and the client is a browser.",
              "Conditional Access reports success because MFA was satisfied by a claim in the token.",
              "A failed sign-in for the same user and IP occurred six minutes earlier.",
            ],
          },
          {
            id: "sentinel-audit-evidence",
            title: "AuditLogs findings",
            category: "cloud",
            facts: [
              "At 02:19 UTC, Jordan added a password credential to application Finance Data Exporter.",
              "The application owner confirms no credential rotation was scheduled.",
              "The new credential has a two-year expiration and the initiating IP matches the sign-in.",
            ],
          },
          {
            id: "sentinel-azure-evidence",
            title: "AzureActivity findings",
            category: "cloud",
            facts: [
              "At 02:27 UTC, Jordan assigned Contributor to Finance Data Exporter on PROD-01.",
              "At 02:31 UTC, the service principal listed storage account keys for prod-finance-data.",
              "Both operations succeeded and no approved change ticket references the application.",
            ],
          },
        ],
        decision: {
          prompt: "Which conclusion is best supported by the correlated records?",
          options: [
            {
              id: "sentinel-sequence-compromise",
              text: "A likely compromised user session created application persistence, granted Azure privilege, and enabled the service principal to access a production storage account.",
              rating: "recommended",
              feedback: "This conclusion explains the shared user, IP, application, resource, timing, and unauthorized changes across all three telemetry sources.",
            },
            {
              id: "sentinel-sequence-validate-user",
              text: "The changes are suspicious, but confirm Jordan's activity and the service principal's later operations before declaring the entire sequence malicious.",
              rating: "acceptable",
              feedback: "Additional validation is reasonable, although the current cross-table evidence already supports urgent containment of the active access paths.",
            },
            {
              id: "sentinel-sequence-mfa-safe",
              text: "The sign-in is trustworthy because Conditional Access succeeded and MFA was present in the token claim.",
              rating: "risky",
              feedback: "A successful control result does not prove the session is legitimate; stolen or replayed tokens can carry previously satisfied MFA claims.",
            },
            {
              id: "sentinel-sequence-separate",
              text: "Treat the role assignment and application credential as unrelated because they appear in different log tables.",
              rating: "risky",
              feedback: "The shared identity, IP, application, resource, and tight timeline strongly support correlation across tables.",
            },
          ],
        },
        outcome: [
          "The investigation timeline connects the anomalous sign-in to a new application credential and privileged Azure role assignment.",
          "The service principal used its new access to retrieve production storage account keys four minutes later.",
        ],
        hint: "Join the evidence conceptually on the account, IP address, application, resource, and bounded time window rather than evaluating each table in isolation.",
        takeaway: "Multi-table correlation turns individual suspicious events into a defensible attack sequence while preserving the uncertainty of each signal.",
        references: [
          { pathId: "path-4", moduleId: "p4-module-3", reason: "Review joins, unions, time-bounded correlation, and multi-table KQL analysis." },
          { pathId: "path-5", moduleId: "p5-module-3", reason: "Review querying Sentinel logs, validating fields, and analyzing results in the workspace." },
        ],
      },
      {
        id: "sentinel-stage-3",
        number: 3,
        title: "Determine the blast radius",
        objective: "Use entities, behavior context, and hunting pivots to find related identities, applications, IP addresses, and resources.",
        briefing: "One user, application, and subscription are confirmed, but the source infrastructure and persistence mechanism may have been used elsewhere in the tenant.",
        evidence: [
          {
            id: "sentinel-entity-context",
            title: "Entity behavior and investigation pivots",
            category: "hunting",
            facts: [
              "Jordan's UEBA page shows the first activity from this ASN and the first credential change performed by the user.",
              "The source IP attempted sign-ins for four other privileged accounts during the previous 24 hours; all failed.",
              "Finance Data Exporter accessed one storage account and queried two Key Vault resources after the role assignment.",
              "A second application received a credential from the same IP seven days earlier, but the operation was performed by a different administrator.",
            ],
          },
        ],
        decision: {
          prompt: "What is the strongest scoping plan?",
          options: [
            {
              id: "sentinel-scope-entities",
              text: "Hunt across the incident window and prior history using the IP, user, application and service-principal IDs, credential changes, role assignments, target resources, and related privileged accounts; bookmark material findings.",
              rating: "recommended",
              feedback: "This tests the compromise hypothesis across identities and resources, uses stable entity identifiers, and preserves the findings that support scope decisions.",
            },
            {
              id: "sentinel-scope-ip",
              text: "Block the source IP and search only for other sign-ins from that address.",
              rating: "acceptable",
              feedback: "The IP is a useful pivot and blocking may reduce immediate risk, but the attacker can change infrastructure while persistent application access remains active.",
            },
            {
              id: "sentinel-scope-incident-only",
              text: "Limit the scope to the entities already present in the incident because Sentinel correlation is exhaustive.",
              rating: "risky",
              feedback: "An incident reflects the rule logic and grouping window; related activity outside those conditions may not be included.",
            },
            {
              id: "sentinel-scope-all-logs",
              text: "Run an unrestricted search across every table and retain every matching event as evidence.",
              rating: "risky",
              feedback: "Unbounded searches create noise and cost without a hypothesis, stable pivots, relevant tables, or a defensible time window.",
            },
          ],
        },
        outcome: [
          "No other successful privileged sign-ins from the source IP are found.",
          "The second application's credential change is validated as an approved rotation from a managed jump host and excluded from the incident.",
          "Finance Data Exporter accessed the production storage account and queried two Key Vaults but did not retrieve secrets from them.",
          "The confirmed scope remains one compromised user session, one persistent application credential, one role assignment, and one accessed storage account.",
        ],
        hint: "Use the incident entities as starting pivots, then test where else those identifiers and behaviors appear inside and outside the original rule window.",
        takeaway: "Sentinel incidents define an initial evidence set, not a guaranteed blast radius; entity-driven hunting is required to confirm scope.",
        references: [
          { pathId: "path-7", moduleId: "p7-module-5", reason: "Review UEBA, entity pages, behavior context, and anomaly-based investigation." },
          { pathId: "path-8", moduleId: "p8-module-2", reason: "Review hunting queries, bookmarks, livestream, and evidence-driven pivots in Sentinel." },
        ],
      },
      {
        id: "sentinel-stage-4",
        number: 4,
        title: "Contain identities and cloud access",
        objective: "Coordinate manual and automated actions against every confirmed access path while retaining analyst control.",
        briefing: "The compromised user session and service-principal credential are still valid. A Sentinel playbook can revoke user sessions, disable the application, and notify the cloud operations team, but destructive resource changes require approval.",
        evidence: [
          {
            id: "sentinel-response-readiness",
            title: "Response controls and playbook status",
            category: "incident",
            facts: [
              "The Contain compromised cloud identity playbook is enabled for on-demand execution and uses a managed identity with approved permissions.",
              "The playbook revokes user sessions, disables the service principal, adds an incident comment, and sends an approval request for credential removal.",
              "The unauthorized Contributor assignment and application credential remain present.",
              "The production storage team is available to rotate the exposed account keys after evidence capture.",
            ],
          },
        ],
        decision: {
          prompt: "Which response plan best matches the confirmed scope?",
          options: [
            {
              id: "sentinel-response-coordinated",
              text: "Run the validated playbook on demand, block Jordan and revoke sessions, disable the service principal, remove the unauthorized credential and role assignment with approval, rotate the exposed storage keys, preserve query results, and verify every action.",
              rating: "recommended",
              feedback: "This contains the user, application, Azure privilege, and exposed resource credential while retaining evidence, approval boundaries, and verification.",
            },
            {
              id: "sentinel-response-immediate-playbook",
              text: "Run the identity-containment playbook immediately, then complete the Azure role and storage-key remediation after the urgent access paths are stopped.",
              rating: "acceptable",
              feedback: "Prioritizing active identity access is defensible, provided ownership and follow-through are explicit for the remaining privilege and exposed keys.",
            },
            {
              id: "sentinel-response-password",
              text: "Reset Jordan's password and close the incident because the original user can no longer authenticate with the old password.",
              rating: "risky",
              feedback: "A password reset alone may not revoke active sessions and does not remove the application credential, role assignment, or exposed storage keys.",
            },
            {
              id: "sentinel-response-auto-delete",
              text: "Create an automation rule that automatically deletes every application credential whenever this analytics rule creates an incident.",
              rating: "risky",
              feedback: "Automatic destructive remediation without validation or approval can interrupt legitimate credential rotations and exceeds the evidence-supported action.",
            },
          ],
        },
        outcome: [
          "Jordan's account is blocked and active sessions are revoked.",
          "Finance Data Exporter is disabled; the malicious credential and unauthorized Contributor assignment are removed.",
          "The production storage account keys are rotated and downstream dependencies are updated by the resource owner.",
          "The playbook records actions in the incident, and the analyst verifies each result in its source system.",
        ],
        hint: "Map one verified action to each access path: user session, service principal, Azure role, and exposed resource credential.",
        takeaway: "Sentinel automation accelerates response, but permissions, approvals, scope validation, and post-action verification remain analyst responsibilities.",
        references: [
          { pathId: "path-7", moduleId: "p7-module-2", reason: "Review automation rules, triggers, conditions, incident tasks, and governance boundaries." },
          { pathId: "path-7", moduleId: "p7-module-3", reason: "Review Sentinel playbooks, Logic Apps, permissions, on-demand execution, and response workflows." },
        ],
      },
      {
        id: "sentinel-stage-5",
        number: 5,
        title: "Close and improve the detection",
        objective: "Verify containment, classify the incident accurately, and tune the rule without hiding future attacks.",
        briefing: "All response actions succeeded. Review the investigation record and decide how to close the incident and improve the analytics rule for future credential-abuse sequences.",
        evidence: [
          {
            id: "sentinel-closure-evidence",
            title: "Validation and detection review",
            category: "incident",
            facts: [
              "No new sign-ins or operations occur for the blocked user or disabled service principal during the monitoring window.",
              "The application credential and role assignment are absent, and the old storage keys no longer authenticate.",
              "The analytics rule correctly detected the attack but grouped only by account, which could separate related service-principal activity into another incident.",
              "One approved jump-host rotation produced a partial match during retrospective testing.",
            ],
          },
        ],
        decision: {
          prompt: "What is the strongest closure and tuning decision?",
          options: [
            {
              id: "sentinel-close-tune",
              text: "Close as a true positive with malicious activity, document the timeline, scope and response, improve entity mappings and grouping for the application, and add a narrow approved-jump-host exclusion that is tested against historical attack data.",
              rating: "recommended",
              feedback: "This preserves an accurate incident record and improves correlation while limiting the exclusion to verified benign infrastructure and testing for detection loss.",
            },
            {
              id: "sentinel-close-monitor",
              text: "Keep the incident Active through an additional monitoring period and assign a documented owner before applying the proposed tuning.",
              rating: "acceptable",
              feedback: "Additional monitoring can be justified by organizational policy, although the current validation supports closure once tuning ownership is recorded.",
            },
            {
              id: "sentinel-close-disable-rule",
              text: "Disable the analytics rule because an approved credential rotation partially matched its logic.",
              rating: "risky",
              feedback: "Disabling the rule removes coverage for a confirmed attack pattern instead of addressing the specific benign condition.",
            },
            {
              id: "sentinel-close-benign",
              text: "Close as a benign positive because the privileged operations used valid credentials and native Azure APIs.",
              rating: "risky",
              feedback: "Valid credentials and native tools are common in identity attacks; the unauthorized sequence and confirmed persistence support malicious activity.",
            },
          ],
        },
        outcome: [
          "The incident is closed as a true positive with malicious activity and retains a complete investigation and response record.",
          "The analytics rule maps both user and cloud-application entities and groups related alerts using account, application, and bounded time criteria.",
          "A narrow exclusion for the managed jump host is documented, peer reviewed, and tested against historical attack events before deployment.",
        ],
        hint: "Tune the precise source of known benign activity while preserving the behavioral sequence and entity coverage that detected the real attack.",
        takeaway: "Good detection engineering converts investigation evidence into safer correlation, narrower exclusions, and more actionable future incidents.",
        references: [
          { pathId: "path-7", moduleId: "p7-module-1", reason: "Review analytics-rule management, scheduling, grouping, mappings, templates, and tuning." },
          { pathId: "path-7", moduleId: "p7-module-4", reason: "Review incident classification, comments, ownership, closure, and investigation records." },
        ],
      },
    ],
    debrief: {
      title: "Cloud persistence removed and Sentinel coverage improved",
      summary: "The attacker used a compromised user session to create an application credential, grant Azure privilege, and access a production resource. The investigation succeeded by correlating multiple tables, expanding from incident entities into hypothesis-driven hunting, containing every identity and cloud access path, and converting the findings into safer analytics-rule tuning.",
      keyLessons: [
        "Validate analytics-rule logic and entity mappings before treating an alert as a complete investigation.",
        "Correlate identity, audit, and Azure activity with shared identifiers and bounded time windows.",
        "Use entity behavior and hunting to establish scope beyond the original incident grouping.",
        "Combine automation with permissions, approvals, evidence preservation, and action verification.",
        "Tune specific benign conditions without suppressing the malicious behavior sequence the rule must detect.",
      ],
    },
  },
  {
    id: "practice-lab-3",
    title: "Investigate and contain a ransomware attempt with Defender for Endpoint",
    subtitle: "Use endpoint evidence to reconstruct execution, find lateral movement, contain affected devices, and recover without destroying forensic value.",
    difficulty: "Intermediate",
    estimatedMinutes: 35,
    primaryDomain: "Respond to security incidents",
    products: ["Microsoft Defender for Endpoint", "Microsoft Defender XDR", "Microsoft Entra ID", "Advanced Hunting"],
    briefing: "Defender XDR correlates suspicious Office child-process activity, credential dumping, remote service creation, and shadow-copy deletion across a finance workstation and two servers. Files are not yet encrypted, but the observed sequence matches ransomware preparation.",
    mission: "Reconstruct the attack, determine which devices and identities are affected, interrupt lateral movement before encryption, preserve useful evidence, and validate a safe recovery path.",
    stages: [
      {
        id: "endpoint-stage-1",
        number: 1,
        title: "Triage the ransomware incident",
        objective: "Prioritize the incident and preserve its correlated endpoint context before taking disruptive action.",
        briefing: "A high-severity Defender XDR incident named Multi-stage incident involving ransomware activity contains alerts from FIN-WS-114, FILE-SRV-02, and APP-SRV-07.",
        evidence: [
          {
            id: "endpoint-incident-summary",
            title: "Incident queue and attack story",
            category: "incident",
            facts: [
              "The incident is New, unassigned, and mapped to Execution, Credential Access, Lateral Movement, and Impact tactics.",
              "The first alert occurred on FIN-WS-114 at 09:42 UTC; server alerts followed 18 minutes later.",
              "Affected entities include three devices, user mia.hammond, a file hash, an external IP, and a remote-service name.",
              "No mass file modification or encryption alert has fired yet.",
            ],
          },
        ],
        decision: {
          prompt: "What is the strongest initial action?",
          options: [
            {
              id: "endpoint-triage-story",
              text: "Assign the incident, set it to Active, validate severity, review the complete attack story and affected entities, and identify which access paths require immediate containment.",
              rating: "recommended",
              feedback: "This establishes ownership and uses the correlated sequence to prioritize containment before the attacker reaches the encryption phase.",
            },
            {
              id: "endpoint-triage-isolate-one",
              text: "Immediately isolate FIN-WS-114 and continue reviewing the server alerts after workstation containment is confirmed.",
              rating: "acceptable",
              feedback: "Isolating the likely initial device can be justified, but the server alerts show that the attacker may already have additional active access paths.",
            },
            {
              id: "endpoint-triage-wait",
              text: "Wait for a file-encryption alert before escalating because ransomware has not yet been confirmed.",
              rating: "risky",
              feedback: "Credential dumping, lateral movement, and shadow-copy deletion are high-confidence precursors; waiting for encryption gives the attacker time to cause impact.",
            },
            {
              id: "endpoint-triage-alerts",
              text: "Investigate every alert independently and close any alert that did not directly modify a file.",
              rating: "risky",
              feedback: "The attack story depends on the relationship among execution, credential theft, remote access, and impact preparation—not on file activity alone.",
            },
          ],
        },
        outcome: [
          "The incident is assigned, moved to Active, and retained at High severity.",
          "FIN-WS-114 is identified as the earliest known device, while both servers are treated as potentially compromised until their timelines are reviewed.",
        ],
        hint: "Ransomware response should begin before encryption when the correlated tactics already show execution, credential access, lateral movement, and impact preparation.",
        takeaway: "A correlated incident provides the sequence and entity context needed to contain ransomware before visible business impact begins.",
        references: [
          { pathId: "path-1", moduleId: "module-2", reason: "Review Defender XDR incident assignment, attack stories, affected assets, severity, and response lifecycle." },
          { pathId: "path-2", moduleId: "p2-module-4", reason: "Review device inventory, device pages, timelines, alerts, logged-on users, and investigation pivots." },
        ],
      },
      {
        id: "endpoint-stage-2",
        number: 2,
        title: "Reconstruct endpoint execution",
        objective: "Use process, file, network, and device-timeline evidence to determine what executed and how the attacker moved.",
        briefing: "The incident graph suggests FIN-WS-114 is the entry point. Review the device timeline and evidence entities before deciding whether the server activity is part of the same attack.",
        evidence: [
          {
            id: "endpoint-process-tree",
            title: "FIN-WS-114 process tree",
            category: "device",
            facts: [
              "WINWORD.EXE opened Invoice_Q4.docm and spawned powershell.exe with an encoded command.",
              "PowerShell downloaded update.dat from hxxps://cdn-finance-support.example and launched it with rundll32.exe.",
              "The payload accessed LSASS memory and created C:\\ProgramData\\cache.bin.",
              "The signed-in user was mia.hammond; the device had no approved administration activity at that time.",
            ],
          },
          {
            id: "endpoint-server-timeline",
            title: "Server timeline findings",
            category: "device",
            facts: [
              "FIN-WS-114 authenticated to FILE-SRV-02 and APP-SRV-07 using Mia's account.",
              "A remote service named WindowsUpdateCheck launched the same cache.bin hash on both servers.",
              "FILE-SRV-02 executed vssadmin.exe delete shadows /all /quiet.",
              "APP-SRV-07 received the payload but behavioral blocking prevented execution.",
            ],
          },
          {
            id: "endpoint-network-evidence",
            title: "Network and file evidence",
            category: "device",
            facts: [
              "FIN-WS-114 and FILE-SRV-02 connected to 203.0.113.84 over TCP 443.",
              "The cache.bin SHA-256 is unknown in the organization and has a malicious cloud verdict.",
              "The download domain was registered nine days ago and appears only on the three incident devices.",
            ],
          },
        ],
        decision: {
          prompt: "Which conclusion is best supported by the endpoint evidence?",
          options: [
            {
              id: "endpoint-analysis-ransomware",
              text: "A malicious document executed a payload on FIN-WS-114, stole or abused Mia's credentials, moved laterally through a remote service, and began ransomware-impact preparation on FILE-SRV-02.",
              rating: "recommended",
              feedback: "This conclusion explains the process ancestry, shared hash, user authentication, remote service, command-and-control activity, and shadow-copy deletion.",
            },
            {
              id: "endpoint-analysis-workstation",
              text: "FIN-WS-114 is compromised, but verify the remote service and shared file hash before classifying both servers as part of the same attack.",
              rating: "acceptable",
              feedback: "Further verification is defensible, although the shared hash, account, service, IP, and sequence already make the connection strong.",
            },
            {
              id: "endpoint-analysis-admin",
              text: "The server operations are likely legitimate because remote services and vssadmin are native Windows administration tools.",
              rating: "risky",
              feedback: "Attackers routinely abuse native tools; legitimacy depends on actor, ancestry, timing, target, authorization, and surrounding evidence.",
            },
            {
              id: "endpoint-analysis-blocked",
              text: "APP-SRV-07 can be excluded from the incident because behavioral blocking prevented the payload from running.",
              rating: "risky",
              feedback: "Prevention reduced impact but the device still received the payload and remote-service activity, so its exposure and persistence must be validated.",
            },
          ],
        },
        outcome: [
          "The initial execution path is traced from the malicious document to PowerShell, rundll32, credential access, and remote-service creation.",
          "FILE-SRV-02 executed the payload and deleted shadow copies; APP-SRV-07 received the payload but blocked execution.",
        ],
        hint: "Focus on parent-child process relationships, shared hashes, user authentication, remote service creation, network destinations, and command timing.",
        takeaway: "Endpoint investigation must explain the complete execution chain and distinguish attempted, blocked, and successful activity on each device.",
        references: [
          { pathId: "path-2", moduleId: "p2-module-4", reason: "Review device timelines, incident links, alerts, logged-on users, and behavioral blocking." },
          { pathId: "path-2", moduleId: "p2-module-6", reason: "Review file, user, IP address, and domain entity investigations in Defender for Endpoint." },
        ],
      },
      {
        id: "endpoint-stage-3",
        number: 3,
        title: "Determine the ransomware scope",
        objective: "Hunt for shared indicators and behaviors across devices and identities without assuming the incident contains every affected asset.",
        briefing: "Three devices are present in the incident, but the payload, remote service, compromised identity, and command-and-control infrastructure may appear elsewhere.",
        evidence: [
          {
            id: "endpoint-hunting-pivots",
            title: "Known hunting pivots",
            category: "hunting",
            facts: [
              "Process pivots: encoded PowerShell, rundll32 loading cache.bin, vssadmin shadow deletion, and service creation with sc.exe.",
              "Entity pivots: Mia's account, cache.bin SHA-256, WindowsUpdateCheck, download domain, and 203.0.113.84.",
              "Relevant data includes DeviceProcessEvents, DeviceFileEvents, DeviceNetworkEvents, DeviceLogonEvents, and DeviceEvents.",
              "The likely attack window begins 30 minutes before document execution and remains open through containment validation.",
            ],
          },
        ],
        decision: {
          prompt: "What is the strongest scoping approach?",
          options: [
            {
              id: "endpoint-scope-behavior",
              text: "Hunt across the endpoint tables using the hash, domain, IP, service name, commands, process ancestry, Mia's logons, and a bounded time window; preserve matching devices and events as investigation evidence.",
              rating: "recommended",
              feedback: "This combines high-confidence indicators with behavior-based pivots and can find related activity even if one observable changes.",
            },
            {
              id: "endpoint-scope-hash",
              text: "Search every device for the malicious file hash and isolate any positive match before performing broader behavior hunting.",
              rating: "acceptable",
              feedback: "The hash is a strong and actionable pivot, but a variant or fileless execution could evade a hash-only search.",
            },
            {
              id: "endpoint-scope-incident",
              text: "Limit containment to the three incident devices because Defender XDR automatically includes every related endpoint.",
              rating: "risky",
              feedback: "Incident correlation is bounded by detections, timing, and grouping logic; related activity can exist outside the incident.",
            },
            {
              id: "endpoint-scope-account",
              text: "Search only for Mia's interactive logons because the attacker cannot move laterally without reusing that same account.",
              rating: "risky",
              feedback: "Attackers can use network logons, tokens, service accounts, local accounts, or remote execution without another interactive logon.",
            },
          ],
        },
        outcome: [
          "The shared hash and service appear only on the three known devices.",
          "Mia's account made a network logon to BACKUP-SRV-01, but no payload, service, suspicious process, or command-and-control activity followed.",
          "A fourth workstation contacted the malicious domain, but SmartScreen blocked the download before file creation or execution.",
          "The confirmed compromise scope is FIN-WS-114 and FILE-SRV-02; APP-SRV-07 remains exposed and requires validation, while the blocked workstation is documented separately.",
        ],
        hint: "Use both observables and behaviors. A single hash finds exact copies; commands, ancestry, services, identities, and network patterns test the broader attack hypothesis.",
        takeaway: "Ransomware scope separates compromised, exposed, and protected devices by correlating what reached, executed, persisted, or was blocked on each asset.",
        references: [
          { pathId: "path-2", moduleId: "p2-module-6", reason: "Review investigation pivots for files, users, IP addresses, and domains across endpoint evidence." },
          { pathId: "path-4", moduleId: "p4-module-3", reason: "Review multi-table KQL correlation for process, file, network, and logon telemetry." },
        ],
      },
      {
        id: "endpoint-stage-4",
        number: 4,
        title: "Contain and preserve evidence",
        objective: "Stop active endpoint and identity access while collecting the evidence needed for remediation and recovery decisions.",
        briefing: "FIN-WS-114 and FILE-SRV-02 are confirmed compromised. APP-SRV-07 blocked execution but received the payload and remote service. Business owners approve emergency containment.",
        evidence: [
          {
            id: "endpoint-response-controls",
            title: "Available response actions",
            category: "device",
            facts: [
              "All three devices are onboarded and healthy in Defender for Endpoint.",
              "Device isolation retains Defender service communication; Live Response and investigation-package collection are permitted.",
              "The malicious file can be quarantined and an organization-wide file indicator can block execution.",
              "Mia's account and sessions remain active; FILE-SRV-02 hosts a critical share with an approved recovery plan.",
            ],
          },
        ],
        decision: {
          prompt: "Which response plan best matches the evidence and business risk?",
          options: [
            {
              id: "endpoint-response-coordinated",
              text: "Isolate the confirmed and exposed devices, revoke Mia's sessions and disable the account, collect investigation packages, use Live Response for targeted validation, quarantine the payload, block confirmed indicators, stop the malicious service, and coordinate server recovery after evidence capture.",
              rating: "recommended",
              feedback: "This interrupts device, identity, payload, service, and network access while retaining evidence and Defender connectivity for validation.",
            },
            {
              id: "endpoint-response-priority",
              text: "Immediately isolate FIN-WS-114 and FILE-SRV-02, revoke Mia's access, then validate APP-SRV-07 before deciding whether its exposure requires continued isolation.",
              rating: "acceptable",
              feedback: "Prioritizing confirmed compromise is defensible if APP-SRV-07 remains actively monitored and its remote-service exposure is resolved promptly.",
            },
            {
              id: "endpoint-response-wipe",
              text: "Wipe all three devices immediately to guarantee removal before collecting packages or reviewing persistence.",
              rating: "risky",
              feedback: "Immediate wiping destroys volatile and forensic evidence, can complicate root-cause analysis, and may not address the compromised identity or other access paths.",
            },
            {
              id: "endpoint-response-file",
              text: "Quarantine cache.bin and close the incident because the known ransomware payload can no longer execute.",
              rating: "risky",
              feedback: "Removing one file does not revoke stolen credentials, remove services or alternate persistence, stop remote access, or validate server integrity.",
            },
          ],
        },
        outcome: [
          "FIN-WS-114, FILE-SRV-02, and APP-SRV-07 are isolated while retaining Defender connectivity.",
          "Mia's account is disabled and active sessions are revoked; investigation packages are collected before destructive remediation.",
          "The malicious file is quarantined, its hash and network indicators are blocked, and WindowsUpdateCheck is removed.",
          "Live Response confirms no additional autoruns or scheduled tasks matching the attack on APP-SRV-07.",
        ],
        hint: "Map containment to the device, identity, payload, persistence, and network paths, and preserve evidence before rebuilding or wiping systems.",
        takeaway: "Effective endpoint containment combines isolation with identity response, evidence collection, targeted remediation, indicator blocking, and verification.",
        references: [
          { pathId: "path-2", moduleId: "p2-module-5", reason: "Review device isolation, antivirus scans, investigation packages, Live Response, and device action governance." },
          { pathId: "path-2", moduleId: "p2-module-8", reason: "Review file and network indicators, alert controls, and detection configuration." },
          { pathId: "path-2", moduleId: "p2-module-7", reason: "Review automated investigation, remediation settings, and blocking at-risk devices." },
        ],
      },
      {
        id: "endpoint-stage-5",
        number: 5,
        title: "Validate recovery and close",
        objective: "Confirm eradication, restore business services safely, classify the incident, and reduce the recurrence risk.",
        briefing: "Containment is complete. FIN-WS-114 will be rebuilt, FILE-SRV-02 will be recovered from a protected backup, and APP-SRV-07 requires final validation before release from isolation.",
        evidence: [
          {
            id: "endpoint-recovery-status",
            title: "Recovery and validation status",
            category: "device",
            facts: [
              "No affected device contacts the command-and-control IP after containment.",
              "Defender Antivirus scans and Live Response checks find no remaining payload, service, or persistence on APP-SRV-07.",
              "FILE-SRV-02 data is restored to a clean replacement host from the last protected backup before shadow-copy deletion.",
              "The malicious document entered through a legacy Office macro workflow; an applicable attack-surface-reduction recommendation remains unimplemented.",
            ],
          },
        ],
        decision: {
          prompt: "What is the strongest closure and recovery decision?",
          options: [
            {
              id: "endpoint-close-validated",
              text: "Release APP-SRV-07 only after validation, rebuild the compromised workstation, recover the file server from the clean backup, close as a true positive with malicious activity, document the full response, and create tracked remediation for the macro and attack-surface-reduction gap.",
              rating: "recommended",
              feedback: "This ties restoration to verified device state, preserves accurate classification, and addresses the control weakness that enabled initial execution.",
            },
            {
              id: "endpoint-close-monitor",
              text: "Keep APP-SRV-07 isolated through an additional monitoring period while restoring the confirmed compromised systems and assigning an owner for the security-control remediation.",
              rating: "acceptable",
              feedback: "Additional validation time can be justified for a critical server, provided ownership, release criteria, and business impact are explicit.",
            },
            {
              id: "endpoint-close-release-all",
              text: "Release every device from isolation once the malicious hash is blocked because the payload cannot run again.",
              rating: "risky",
              feedback: "A hash block does not prove removal of alternate payloads, persistence, compromised credentials, or damaged system state.",
            },
            {
              id: "endpoint-close-false",
              text: "Close as a false positive because behavioral blocking prevented encryption from completing.",
              rating: "risky",
              feedback: "Prevention reduced impact but does not make the confirmed execution, credential abuse, lateral movement, and shadow-copy deletion benign.",
            },
          ],
        },
        outcome: [
          "APP-SRV-07 passes validation and is released from isolation under enhanced monitoring.",
          "FIN-WS-114 is rebuilt and FILE-SRV-02 is restored to a clean replacement host before production access resumes.",
          "The incident is closed as a true positive with malicious activity and records the timeline, scope, evidence, actions, validation, and recovery decisions.",
          "A security recommendation is assigned to restrict Office child processes and retire the legacy macro workflow.",
        ],
        hint: "Recovery is complete only when eradication is verified, business data is restored from a trusted point, the incident is documented, and the enabling control gap has an owner.",
        takeaway: "Ransomware closure combines technical validation, trusted recovery, evidence-backed classification, and measurable reduction of the original attack path.",
        references: [
          { pathId: "path-2", moduleId: "p2-module-5", reason: "Review device actions and validation techniques used before releasing isolated assets." },
          { pathId: "path-2", moduleId: "p2-module-9", reason: "Review security recommendations, vulnerability exposure, remediation ownership, and risk reduction." },
          { pathId: "path-1", moduleId: "module-2", reason: "Review true-positive classification, incident documentation, response tracking, and closure." },
        ],
      },
    ],
    debrief: {
      title: "Encryption prevented and recovery completed from trusted state",
      summary: "The attacker used a malicious document to execute code, access credentials, move laterally, and prepare a file server for ransomware impact. The response prevented encryption by correlating endpoint behavior early, distinguishing compromised from exposed devices, containing both endpoint and identity access, preserving evidence before remediation, and validating recovery from trusted sources.",
      keyLessons: [
        "Treat ransomware precursor behaviors as an opportunity to contain before encryption, not a reason to wait for impact.",
        "Use process ancestry, device timelines, shared entities, and network activity to reconstruct lateral movement.",
        "Scope with both exact indicators and behavior-based hunting across endpoint telemetry.",
        "Preserve evidence before wiping or rebuilding, and map response actions to every active access path.",
        "Validate eradication and trusted recovery before release, then remediate the control gap that enabled execution.",
      ],
    },
  },
  {
    id: "practice-lab-4",
    title: "Investigate a compromised cloud workload with Defender for Cloud",
    subtitle: "Correlate workload alerts and posture findings to contain a compromised VM and remove the attack path that exposed it.",
    difficulty: "Intermediate",
    estimatedMinutes: 35,
    primaryDomain: "Mitigate threats using Microsoft Defender for Cloud",
    products: ["Microsoft Defender for Cloud", "Defender for Servers", "Azure Resource Manager", "Microsoft Sentinel"],
    briefing: "Defender for Cloud raises alerts for suspicious authentication, a crypto-mining process, and unusual Key Vault access involving an internet-facing Azure VM. The workload belongs to a production analytics application and uses a managed identity with access to several cloud resources.",
    mission: "Validate the compromise, reconstruct the workload and control-plane activity, determine the affected resources, contain the attacker while preserving evidence, and remediate the posture weaknesses that created the attack path.",
    stages: [
      {
        id: "cloud-stage-1",
        number: 1,
        title: "Triage the cloud security alerts",
        objective: "Prioritize the alert cluster and validate workload context, coverage, and exposed attack paths.",
        briefing: "Three high-severity alerts reference VM az-prod-analytics-03 in subscription PROD-DATA. Defender for Servers is enabled and the alerts are also connected to a Microsoft Sentinel incident.",
        evidence: [
          {
            id: "cloud-alert-summary",
            title: "Defender for Cloud alert summary",
            category: "incident",
            facts: [
              "Alerts: successful SSH brute-force sign-in, detected crypto-mining behavior, and anomalous Key Vault operation by a managed identity.",
              "The first successful SSH session occurred at 03:18 UTC from 203.0.113.206; mining activity began seven minutes later.",
              "Resource context shows a public IP and an NSG rule allowing TCP 22 from Internet.",
              "The VM is production tagged, has no approved maintenance window, and remains online.",
            ],
          },
          {
            id: "cloud-coverage-summary",
            title: "Protection and posture context",
            category: "cloud",
            facts: [
              "Defender for Servers Plan 2 and agentless scanning are enabled for the subscription.",
              "The VM has a system-assigned managed identity and belongs to the analytics-prod resource group.",
              "A high-severity recommendation to close management ports has been unhealthy for 19 days.",
              "The recommendation has no exemption, owner, or remediation due date.",
            ],
          },
        ],
        decision: {
          prompt: "What is the strongest initial action?",
          options: [
            {
              id: "cloud-triage-correlate",
              text: "Assign and activate the incident, review the Defender for Cloud alert timelines and affected resources, validate the open-management-port attack path, and identify the workload and identity access that require urgent containment.",
              rating: "recommended",
              feedback: "This connects threat alerts to workload context and the posture weakness that enabled access, while establishing ownership before response.",
            },
            {
              id: "cloud-triage-stop-vm",
              text: "Stop the VM immediately to interrupt mining, then investigate identity and Key Vault activity after the workload is offline.",
              rating: "acceptable",
              feedback: "Stopping the VM can reduce active impact, but evidence, managed-identity access, network controls, and business recovery still require coordinated handling.",
            },
            {
              id: "cloud-triage-suppress",
              text: "Suppress the crypto-mining alert because production analytics workloads normally consume substantial CPU.",
              rating: "risky",
              feedback: "Resource consumption alone can be benign, but the correlated SSH compromise and anomalous Key Vault access make suppression unsupported.",
            },
            {
              id: "cloud-triage-recommendation",
              text: "Remediate the open SSH recommendation and close the alerts without reviewing the activity that already occurred.",
              rating: "risky",
              feedback: "Closing the exposure does not remove an attacker, persistence, stolen secrets, or malicious processes already present on the workload.",
            },
          ],
        },
        outcome: [
          "The alerts are confirmed as a connected sequence involving external access, workload execution, and managed-identity activity.",
          "The open SSH rule is identified as an active attack path rather than a standalone hygiene issue.",
        ],
        hint: "Use both sides of Defender for Cloud: workload-protection alerts explain what happened, while posture recommendations explain how the resource was exposed.",
        takeaway: "Cloud incident triage combines alert evidence, resource context, protection coverage, and the posture weaknesses that form a practical attack path.",
        references: [
          { pathId: "path-3", moduleId: "p3-module-6", reason: "Review Defender for Cloud alerts, affected resources, remediation, response automation, suppression, and threat-intelligence context." },
          { pathId: "path-3", moduleId: "p3-module-4", reason: "Review recommendations, Secure Score, governance, compliance, and cloud posture prioritization." },
        ],
      },
      {
        id: "cloud-stage-2",
        number: 2,
        title: "Reconstruct workload and identity activity",
        objective: "Determine what executed on the VM and whether the workload identity was used to access other cloud resources.",
        briefing: "The alert cluster confirms suspicious activity, but containment depends on understanding the attacker session, processes, persistence, outbound traffic, and managed-identity operations.",
        evidence: [
          {
            id: "cloud-vm-evidence",
            title: "VM process and network evidence",
            category: "device",
            facts: [
              "The SSH session authenticated as legacyops using a password from 203.0.113.206.",
              "The session downloaded /tmp/azmon from mining-update.example and launched it as a systemd service named az-health-agent.",
              "The binary opened a persistent connection to 198.51.100.92:4444 and consumed more than 90 percent CPU.",
              "The attacker queried the Azure Instance Metadata Service for a managed-identity token.",
            ],
          },
          {
            id: "cloud-identity-evidence",
            title: "Managed identity and Key Vault evidence",
            category: "identity",
            facts: [
              "The VM identity requested a token for Azure Key Vault six minutes after payload execution.",
              "It listed secrets in kv-prod-analytics and retrieved db-export-password.",
              "The identity has Key Vault Secrets User on two vaults, but only kv-prod-analytics shows access during the incident window.",
              "The application owner confirms the VM normally reads one different secret through the application, never through an interactive shell sequence.",
            ],
          },
          {
            id: "cloud-control-plane-evidence",
            title: "Azure control-plane evidence",
            category: "cloud",
            facts: [
              "No NSG, role-assignment, disk, snapshot, or extension changes were made during the incident.",
              "The legacyops local account was added to sudoers two weeks earlier by an approved deployment script, but password authentication should have been disabled afterward.",
              "The exposed password appears in an expired operations handoff document.",
            ],
          },
        ],
        decision: {
          prompt: "Which conclusion is best supported by the evidence?",
          options: [
            {
              id: "cloud-analysis-compromise",
              text: "An attacker authenticated through exposed SSH credentials, established mining persistence, obtained the VM managed-identity token, and used its excessive Key Vault permission to retrieve a production secret.",
              rating: "recommended",
              feedback: "This conclusion explains the authentication, process, persistence, outbound network, metadata-service, identity, and Key Vault sequence.",
            },
            {
              id: "cloud-analysis-mining-only",
              text: "The VM is compromised for crypto-mining, but validate the managed-identity token and Key Vault operation before treating the production secret as exposed.",
              rating: "acceptable",
              feedback: "Additional validation is reasonable, although the token request and successful secret retrieval already justify treating the secret as compromised.",
            },
            {
              id: "cloud-analysis-normal-identity",
              text: "The Key Vault activity is benign because the managed identity already had permission to read secrets.",
              rating: "risky",
              feedback: "Authorization does not establish legitimacy; the operation occurred inside an attacker-controlled session and differed from the workload's normal behavior.",
            },
            {
              id: "cloud-analysis-no-control-plane",
              text: "The incident affects only CPU capacity because no Azure control-plane configuration was changed.",
              rating: "risky",
              feedback: "Workload compromise, persistence, identity-token theft, and data-plane secret access can occur without any Resource Manager configuration change.",
            },
          ],
        },
        outcome: [
          "The attack path is reconstructed from exposed SSH to workload execution, persistence, metadata-token acquisition, and Key Vault secret retrieval.",
          "The production database credential is treated as compromised even though no control-plane change occurred.",
        ],
        hint: "Separate control-plane operations from workload and data-plane activity; the absence of Resource Manager changes does not make the VM or secret safe.",
        takeaway: "Cloud workload investigations must correlate host activity, resource configuration, identity tokens, and downstream data-plane access.",
        references: [
          { pathId: "path-3", moduleId: "p3-module-5", reason: "Review Defender for Servers, Key Vault, Resource Manager, DNS, Storage, and other workload-protection signals." },
          { pathId: "path-3", moduleId: "p3-module-6", reason: "Review alert evidence and response workflows for compromised Azure resources." },
        ],
      },
      {
        id: "cloud-stage-3",
        number: 3,
        title: "Determine the cloud blast radius",
        objective: "Use asset inventory, alert pivots, identities, and configuration relationships to separate compromised from similarly exposed resources.",
        briefing: "The subscription contains other analytics VMs created from the same template. The source IP, binary, local account, managed identity permissions, and public-management exposure are investigation pivots.",
        evidence: [
          {
            id: "cloud-scope-pivots",
            title: "Asset inventory and scope pivots",
            category: "hunting",
            facts: [
              "Asset inventory lists six VMs with the analytics-prod tag; three have public IP addresses.",
              "Two VMs share the legacyops account and internet-wide SSH rule; only az-prod-analytics-03 shows the malicious binary, service, IP, or mining alert.",
              "The source IP attempted SSH against the second exposed VM but did not authenticate.",
              "The managed identity is unique to az-prod-analytics-03; the retrieved database secret was not accessed by another unexpected principal.",
            ],
          },
          {
            id: "cloud-secret-scope",
            title: "Downstream secret-use review",
            category: "cloud",
            facts: [
              "Database authentication logs show no successful use of db-export-password from a new source after retrieval.",
              "The secret grants read access to an export database but not administrative or write access.",
              "No other secret in either permitted vault was retrieved during the attack window.",
            ],
          },
        ],
        decision: {
          prompt: "What is the strongest scoping plan?",
          options: [
            {
              id: "cloud-scope-relations",
              text: "Pivot across asset inventory, alerts, the source IP and binary, local-account configuration, public SSH exposure, managed-identity permissions, Key Vault operations, and downstream use of the retrieved credential.",
              rating: "recommended",
              feedback: "This scopes the compromise and the attack path across assets, configuration, identity, secrets, and downstream resources without equating exposure with successful compromise.",
            },
            {
              id: "cloud-scope-exposed",
              text: "Treat both VMs with the shared account and public SSH rule as compromised and isolate them while deeper validation continues.",
              rating: "acceptable",
              feedback: "Precautionary containment can be justified for high-risk exposure, but investigation records should distinguish confirmed compromise from exposure and failed access.",
            },
            {
              id: "cloud-scope-alert-only",
              text: "Limit the scope to az-prod-analytics-03 because Defender for Cloud did not create alerts for any other resource.",
              rating: "risky",
              feedback: "Alerts reflect observed detections; inventory, configuration, identity, and downstream data can reveal related risk or activity without an alert.",
            },
            {
              id: "cloud-scope-public-all",
              text: "Declare every VM with a public IP compromised and begin rebuilding all of them immediately.",
              rating: "risky",
              feedback: "A public IP is exposure context, not proof of successful access or malicious execution; indiscriminate rebuilding creates unnecessary impact and destroys evidence.",
            },
          ],
        },
        outcome: [
          "az-prod-analytics-03 is the only confirmed compromised workload.",
          "az-prod-analytics-02 is classified as critically exposed after a failed attack attempt and requires immediate hardening and credential removal.",
          "The remaining analytics VMs have no matching indicators and do not expose SSH to the internet.",
          "The retrieved database credential shows no observed abuse, but remains compromised and requires rotation.",
        ],
        hint: "Scope both the malicious activity and the enabling configuration, but record separately what was compromised, attempted, exposed, and unaffected.",
        takeaway: "Cloud blast radius is established through resource relationships and identity access, not simply by counting alerts or public endpoints.",
        references: [
          { pathId: "path-3", moduleId: "p3-module-2", reason: "Review Defender for Cloud asset inventory, resource filtering, coverage status, and provisioning context." },
          { pathId: "path-3", moduleId: "p3-module-4", reason: "Review recommendations, affected resources, attack-path prioritization, and posture governance." },
        ],
      },
      {
        id: "cloud-stage-4",
        number: 4,
        title: "Contain the workload and access paths",
        objective: "Stop compute, network, identity, and secret access while preserving evidence and maintaining a controlled recovery path.",
        briefing: "The compromised VM is still mining and its managed identity can still access Key Vault. The second VM remains exposed to SSH but shows no successful compromise.",
        evidence: [
          {
            id: "cloud-response-readiness",
            title: "Response readiness and dependencies",
            category: "cloud",
            facts: [
              "The production team can drain analytics traffic to a healthy scale-set instance.",
              "Network controls can quarantine the compromised VM while retaining access from an approved forensic subnet.",
              "A disk snapshot can be captured before rebuilding; the managed identity can be disabled and its role assignments removed.",
              "The database owner can rotate db-export-password and confirm application updates within the response window.",
            ],
          },
        ],
        decision: {
          prompt: "Which response plan best addresses the confirmed scope and attack path?",
          options: [
            {
              id: "cloud-response-coordinated",
              text: "Drain traffic, quarantine the compromised VM, capture disk and relevant log evidence, disable the managed identity and remove excessive roles, rotate the database secret, close public SSH on both exposed VMs, remove the legacy account, and rebuild the compromised workload from a trusted image.",
              rating: "recommended",
              feedback: "This contains compute, network, identity, credential, and configuration paths while preserving evidence and supporting controlled recovery.",
            },
            {
              id: "cloud-response-quarantine-first",
              text: "Immediately quarantine az-prod-analytics-03 and disable its identity, then coordinate evidence capture, secret rotation, exposure remediation, and trusted rebuild.",
              rating: "acceptable",
              feedback: "Prioritizing active access is defensible when mining and identity abuse continue, provided evidence and remaining remediation have explicit ownership.",
            },
            {
              id: "cloud-response-delete",
              text: "Delete the VM and its disks immediately, then redeploy the same template to restore production quickly.",
              rating: "risky",
              feedback: "Deletion destroys evidence, leaves the exposed template and credentials unchanged, and can recreate the same attack path.",
            },
            {
              id: "cloud-response-nsg-only",
              text: "Close the internet SSH rule and release the VM because the attacker can no longer establish a new inbound session.",
              rating: "risky",
              feedback: "The attacker already has persistence, an outbound channel, a managed-identity token path, and a retrieved secret; network hardening alone is insufficient.",
            },
          ],
        },
        outcome: [
          "Traffic is drained and the compromised VM is quarantined with forensic access retained.",
          "Disk and alert evidence is preserved before the VM is rebuilt from a patched, hardened image.",
          "The managed identity is disabled, excessive roles are removed, and db-export-password is rotated and redeployed.",
          "Public SSH and the legacyops account are removed from both exposed VMs; administration moves to an approved private access path.",
        ],
        hint: "Map response to the workload process, persistence, inbound exposure, outbound channel, managed identity, retrieved secret, and vulnerable deployment template.",
        takeaway: "Cloud containment must address the running workload and the surrounding identities, secrets, network paths, and infrastructure configuration that sustain access.",
        references: [
          { pathId: "path-3", moduleId: "p3-module-6", reason: "Review response actions, automation, suppression safeguards, threat reports, and alert remediation for Azure resources." },
          { pathId: "path-3", moduleId: "p3-module-5", reason: "Review workload protections for Servers, Key Vault, Resource Manager, DNS, and related cloud services." },
        ],
      },
      {
        id: "cloud-stage-5",
        number: 5,
        title: "Validate recovery and improve posture",
        objective: "Verify eradication, close accurately, and convert incident findings into governed posture improvements.",
        briefing: "The workload has been rebuilt and restored behind private administration controls. Validate recovery and decide how recommendations, Secure Score, and governance should reflect the incident lessons.",
        evidence: [
          {
            id: "cloud-validation-status",
            title: "Recovery and posture validation",
            category: "cloud",
            facts: [
              "The replacement VM uses a hardened image, private administration, key-based access, current patches, and no legacyops account.",
              "No mining process, persistence service, malicious outbound traffic, or anomalous identity activity appears during monitoring.",
              "The rotated database credential succeeds only from approved application identities.",
              "The management-port recommendation is healthy for both affected VMs, but four development VMs in another subscription remain unhealthy.",
            ],
          },
          {
            id: "cloud-governance-status",
            title: "Governance and Secure Score context",
            category: "cloud",
            facts: [
              "The original recommendation remained unresolved because it had no owner or due date.",
              "A governance rule can assign high-severity internet-exposure recommendations to the Cloud Platform team with a seven-day remediation target.",
              "No business justification supports an exemption for unrestricted management ports.",
            ],
          },
        ],
        decision: {
          prompt: "What is the strongest closure and posture decision?",
          options: [
            {
              id: "cloud-close-governed",
              text: "Close as a true positive with malicious activity, document the workload-to-identity attack path and response, assign governed remediation for every remaining public-management exposure, set owners and due dates, and monitor the recommendation and Secure Score trend.",
              rating: "recommended",
              feedback: "This records the confirmed incident accurately and converts the enabling posture gap into measurable, owned remediation across the environment.",
            },
            {
              id: "cloud-close-production",
              text: "Close the incident after validating production recovery and create a separate tracked posture initiative for the remaining development exposures.",
              rating: "acceptable",
              feedback: "Separating incident closure from broader posture work is reasonable if the remaining risk has named ownership, scope, priority, and deadlines.",
            },
            {
              id: "cloud-close-exempt-dev",
              text: "Exempt every development VM from the management-port recommendation because they are not production workloads.",
              rating: "risky",
              feedback: "Environment tier does not remove attack-path risk; exemptions require specific business justification, compensating controls, scope, and expiration.",
            },
            {
              id: "cloud-close-benign",
              text: "Close as a benign positive because crypto-mining consumed compute but did not alter the application or database.",
              rating: "risky",
              feedback: "Unauthorized execution, persistence, identity-token abuse, and secret retrieval are malicious even when destructive data impact is not observed.",
            },
          ],
        },
        outcome: [
          "The incident is closed as a true positive with malicious activity and documents the full attack path, scope, evidence, response, and validation.",
          "High-severity public-management recommendations receive owners, seven-day due dates, and escalation through a governance rule.",
          "The remaining development exposures enter tracked remediation without broad exemptions, and posture progress is monitored through recommendations and Secure Score.",
        ],
        hint: "A closed incident should leave behind an accurate record and a governed mechanism that prevents the same posture weakness from remaining indefinitely elsewhere.",
        takeaway: "Defender for Cloud connects threat response to posture management by turning the attack path into prioritized, owned, and measurable remediation.",
        references: [
          { pathId: "path-3", moduleId: "p3-module-4", reason: "Review Secure Score, recommendations, governance, exemptions, compliance, and posture monitoring." },
          { pathId: "path-3", moduleId: "p3-module-6", reason: "Review alert classification, remediation, response, automation, suppression, and closure." },
        ],
      },
    ],
    debrief: {
      title: "Compromised workload rebuilt and its cloud attack path removed",
      summary: "The attacker used exposed SSH credentials to compromise a production VM, establish mining persistence, obtain a managed-identity token, and retrieve a Key Vault secret. The response succeeded by correlating workload, identity, data-plane, and posture evidence; distinguishing compromise from exposure; containing every access path; preserving evidence; and governing the same security recommendation across the environment.",
      keyLessons: [
        "Use workload-protection alerts and posture recommendations together to understand both activity and exposure.",
        "Investigate host, control-plane, identity, and data-plane evidence even when no Azure configuration was changed.",
        "Distinguish confirmed compromise, failed attempts, critical exposure, and unaffected resources during cloud scoping.",
        "Contain compute, network, identity, secret, and infrastructure-template paths before trusted recovery.",
        "Convert incident findings into owned recommendations, deadlines, and measurable posture improvement rather than broad exemptions.",
      ],
    },
  },
];
